### ISSUE TITLE
How to convert simple_switch_CLI commands to JSON?

### ISSUE THREAD

**Issue by gogamid** [p4lang/behavioral-model#1000]
I need to heave these commands loaded with switch when I make. I need to convert them to JSON and put it in tutorials/exercises/basic/pod-topo/s1-runtime.json. I am using simple_switch_CLI. 

```
act_prof_create_group mp_profile
act_prof_create_member mp_profile _nop
act_prof_create_member mp_profile set_mp_port 3
act_prof_create_member mp_profile set_mp_port 4
act_prof_create_member mp_profile set_mp_port 5
act_prof_create_member mp_profile _drop
act_prof_add_member_to_group mp_profile 1 0
act_prof_add_member_to_group mp_profile 2 0
act_prof_add_member_to_group mp_profile 3 0
act_prof_add_member_to_group mp_profile 4 0
table_indirect_set_default mp_profile_forward 0
table_indirect_add_with_group mp_profile_forward 10.0.0.10 10.0.2.10 => 0
table_indirect_add_with_group mp_profile_forward 10.0.0.10 10.0.3.10 => 0
table_indirect_add_with_group mp_profile_forward 10.0.1.10 10.0.2.10 => 0
table_indirect_add_with_group mp_profile_forward 10.0.1.10 10.0.3.10 => 0
table_dump mp_profile_forward
```

**Comment by jafingerhut** [comment]
The tutorials JSON files with names like s1-runtime.json are read by Python programs that are included as part of the p4lang/tutorials repository, which then issues P4Runtime API messages to simple_switch_grpc to cause the desired things to happen.

The format of the tutorials JSON data is custom to the p4lang/tutorials repository, and to my knowledge exists in no other software anywhere in the world.

They were written by people who created the tutorials and didn't want to make people learn P4Runtime API programming yet, I believe.  They developed it to support the subset of P4 configuration features that they needed for the tutorials exercises, and no others, so that Python code probably doesn't support the configuration actions you want.

You could extend those Python programs yourself to do that, if you were interested in doing that, but the longer term more useful thing to learn, if you really want to write dynamic controller code, is to learn how to create P4Runtime API messages from your controller code.  That will give you full access to configuring anything that the P4Runtime API can configure, which includes action profiles, action selectors, multicast groups, etc.

**Comment by jafingerhut** [comment]
The Python code I am linking here does not do everything you want, either, e.g. it does not support action profiles or action selector configuration, for example, but it does support multicast configuration.  You might consider extending it to do what you want, and depending upon how you did so, I might be interested in including such extensions into this published code for others to use:

https://github.com/jafingerhut/p4-guide/blob/master/testlib/base_test.py

Note that code is Python3 only.  I can point you at a pre-built Ubuntu 20.04 Linux VM that has the P4 open source tools already compiled, and has modifications to the tutorials repo code that is more Python 3 friendly, if that is of interest to you.

**Comment by rst0git** [comment]
> I need to heave these commands loaded with switch when I make.

You can also use the Thrift API by replacing `"runtime_json"` with `"cli_input"` in your `topology.json` ([example](https://github.com/mtpsa/mtpsa-examples/blob/e1aed066bde2c9e0ea4259f9272d13a5f3483e7e/src/basic/topology/topology.json#L113)).

**Comment by gogamid** [comment]
Thanks, @rst0git   that's what I needed for now

@jafingerhut I will dive into Python soon.
