### ISSUE TITLE
Deparser cannot support both TCP and UDP simultaneously

### ISSUE THREAD

**Issue by crx892476808** [p4lang/behavioral-model#1009]
When there are both UDP data packets and TCP data packets in the network, Bmv2 cannot work because the deparser cannot emit L4 header according to the protocol field of the IP header (IF statement is not supported in deparser)

Can anyone deal with it ?

**Comment by jfingerh** [comment]
Every 'emit' statement has built into it the condition "if this header is currently valid, copy its contents into the output packet, otherwise do nothing".  The way people typically write deparsers is to emit tcp and udp headers in an arbitrary order.  As long as at most one of them is valid, you get the packet you wants.

**Comment by crx892476808** [comment]
> Every 'emit' statement has built into it the condition "if this header is currently valid, copy its contents into the output packet, otherwise do nothing". The way people typically write deparsers is to emit tcp and udp headers in an arbitrary order. As long as at most one of them is valid, you get the packet you wants.

I try, and it works. Thank you very much!
