### ISSUE TITLE
Consider making it a command line option to enable priority queues

### ISSUE THREAD

**Issue by jafingerhut** [p4lang/behavioral-model#1065]
Right now with no source code changes, I believe that bmv2 supports one FIFO packet queue per output port in its traffic manager.

There is already code that implements multiple FIFO packet queues per output port, with a packet scheduler in software between these multiple queues to select which queue a packet is sent to the output port next for that output port.  Right now enabling this feature requires changing one #define line in the source code and recompiling.

I suspect it might not be a lot of effort to change this situation, so that a command line option could be used to choose between these options at bmv2 start time, without having to recompile.

**Comment by jafingerhut** [comment]
For anyone interested in working on this, here is an earlier issues with the source code changes currently required to use the "change the source code, then recompile" approach: https://github.com/p4lang/behavioral-model/issues/877

**Comment by antoninbas** [comment]
I think this is a good idea. The original argument of the compile-time approach leading to better performance seems a bit moot given the overall bmv2 performance and the fact that each packet only interacts with the queueing logic twice.

**Comment by duskmoon314** [comment]
Hello. In my recent work, the priority queue is very useful. Now I would like to try to implement the "configurable" feature mentioned in this issue. But I'm not familiar with the internal implementation of bmv2 and I haven't written CPP for a while. So I would like to share my initial changes first so that you can review whether the approach is appropriate.

First, the following discussion is about `simple_switch` for now. I haven't used other targets, so I'm willing to implement the feature on `simple_switch` first.

I think that a `QueueingLogicPriRL` with only 1 priority is the same as a `QueueingLogicRL`. So I think the definition of `SimpleSwitch` should be changed to:

```diff
+ size_t nb_queues = 1u;
+ bm::QueueingLogicPriRL<std::unique_ptr<Packet>, EgressThreadMapper>
- bm::QueueingLogicRL<std::unique_ptr<Packet>, EgressThreadMapper>
```

Member `nb_queues` takes the place of macro `SSWITCH_PRIORITY_QUEUEING_NB_QUEUES` so we can add a method to configure the number of queues during the running:

```cpp
void
SimpleSwitch::set_priority_queues(size_t queues) {
  nb_queues = queues;
  egress_buffers.~QueueingLogicPriRL();
  new(&egress_buffers) bm::QueueingLogicPriRL<std::unique_ptr<Packet>, EgressThreadMapper>(
				   nb_egress_threads,
                   64, EgressThreadMapper(nb_egress_threads),
                   nb_queues);
}
```
This is where I am most unsure how to achieve. I found how to reconstruct an object [here](https://stackoverflow.com/questions/2166099/calling-a-constructor-to-re-initialize-object). But it seems that it may not be a good practice. I wish someone could give me some advice on how to recreate all the queues.

In addition to the above, we should make this method be seen in `simple_switch_CLI`. Then it seems no other changes are needed.

I have already made these changes on my computer and passed the test via `make check`. I will check whether this can work when trying to update the number of priorities.

---

Besides, the URL of CLA needs to be updated.

**Comment by antoninbas** [comment]
> I think that a QueueingLogicPriRL with only 1 priority is the same as a QueueingLogicRL

I think that may be a valid observation, and a good way to keep the code simple when implementing this issue.

> Member nb_queues takes the place of macro SSWITCH_PRIORITY_QUEUEING_NB_QUEUES so we can add a method to configure the number of queues during the running:
> This is where I am most unsure how to achieve. I found how to reconstruct an object here. But it seems that it may not be a good practice. I wish someone could give me some advice on how to recreate all the queues.

I don't think that's the right approach. IMO, being able to set the number of queues at start time (through the command line) is good enough. There is no need to be able to make arbitrary changes at runtime to the number of queues (e.g. through simple_switch_CLI), which has other implications (such as, what happens to the packets which are currently queued?).

To clarity further, this issue is about adding a command line option so that the `simple_switch` and `simple_switch_grpc` programs can be invoked with a specific number of priority queues, the default being 1:
```
simple_switch[_grpc] --priority-queues <N>
```
You can then use that number when constructing the `QueueingLogicPriRL` instance. It will not be changed thereafter.

**Comment by duskmoon314** [comment]
> To clarify further, this issue is about adding a command line option

I see. Very clarified. Thanks. I will try to implement it this way

**Comment by duskmoon314** [comment]
I have changed my implementation according to the suggestions of @antoninbas. This time I add a command-line option `--priority-queues <N>` to the simple_switch_parser in `targets/simple_switch_grpc/main.cpp`.

For now, the usage is like this:

```
simple_switch -i 1@s1-eth1 -i 2@s1-eth2 test_prio.json -- --priority-queues 8
```

I think you would like to check this [commit](https://github.com/duskmoon314/behavioral-model/commit/34109d921eecbf46d80858d74694f2e0d6adf5a0) first.

TODO:
- A better commit message
- Maybe write a test for switch with priority

**Comment by antoninbas** [comment]
@duskmoon314 please open a PR if you want a review

**Comment by AmeyAvhad** [comment]
Ok so according to my understanding the priority queues implementation is now possible and we can make n no. of priority queues using 
`simple_switch -i 1@s1-eth1 -i 2@s1-eth2 test_prio.json -- --priority-queues 8`

Sorry to ask but I am new to this so I would like to ask for how to use this priority queue feature in my p4 program regarding how to assign queues and stuff.

**Comment by jafingerhut** [comment]
There is a field named `priority` in the v1model architecture standard_metadata struct: https://github.com/p4lang/p4c/blob/main/p4include/v1model.p4#L111-L113

During ingress processing, you should assign a value to that field.  The value of that field when ingress processing is done is used to select one of several priority queues for the same output port.

**Comment by maruf23081999** [comment]
> I have changed my implementation according to the suggestions of @antoninbas. This time I add a command-line option `--priority-queues <N>` to the simple_switch_parser in `targets/simple_switch_grpc/main.cpp`.
> 
> For now, the usage is like this:
> 
> ```
> simple_switch -i 1@s1-eth1 -i 2@s1-eth2 test_prio.json -- --priority-queues 8
> ```
> 
> I think you would like to check this [commit](https://github.com/duskmoon314/behavioral-model/commit/586c68edd7501c053df85ccb27eb160aac6674bc) first.
> 
> TODO:
> 
> * A better commit message
> * Maybe write a test for switch with priority

what is test_prio.json

**Comment by duskmoon314** [comment]
> what is test_prio.json

That is just a JSON file from p4c, which I used to test my implementation.

You may want to read the [README](https://github.com/p4lang/behavioral-model/tree/main?tab=readme-ov-file#running-your-p4-program) first.

**Comment by maruf23081999** [comment]
> > what is test_prio.json
> 
> That is just a JSON file from p4c, which I used to test my implementation.
> 
> You may want to read the [README](https://github.com/p4lang/behavioral-model/tree/main?tab=readme-ov-file#running-your-p4-program) first.

when i tried using the command it works and server listening on 0.0.0.0:9559 but then i cannot use my p4 program sudo python3 network.py as it gives error that s1 cannot bind port 9090 because it is bound by another process.

**Comment by jafingerhut** [comment]
@maruf23081999 I would recommend asking such questions in https://forum.p4.org where more people read the messages and might respond to them.  Your questions are not really bugs or enhancements in the BMv2 program, but questions on how to use it properly.
