### ISSUE TITLE
bmv2 switch based on simple_switch_grpc not able to work on any other thrift port other than 9559

### ISSUE THREAD

**Issue by hkaur-hsc** [p4lang/behavioral-model#1116]
I am trying to run the sample mininet program 1sw_demo.py from this repo as follows:
**python ./behavioral-model/mininet/1sw_demo.py --behavioral-exe behavioral-model//targets/simple_switch_grpc/simple_switch_grpc --thrift-port 9090 --json p4Programs/basic.json**

_root@GGNLABDTE00059:~# python ./behavioral-model/mininet/1sw_demo.py --behavioral-exe behavioral-model//targets/simple_switch_grpc/simple_switch_grpc --thrift-port 9090 --json p4Programs/basic.json
*** Creating network
*** Adding hosts:
h1 h2
*** Adding switches:
s1
*** Adding links:
(h1, s1) (h2, s1)
*** Configuring hosts
h1 h2
*** Starting controlle
*** Starting 1 switches
s1 Starting P4 switch s1.
behavioral-model//targets/simple_switch_grpc/simple_switch_grpc -i 1@s1-eth1 -i 2@s1-eth2 --thrift-port 9090 --nanolog ipc:///tmp/bm-0-log.ipc --device-id 0 p4Programs/basic.json_

This gets stuck and further investigation indicates that it is not able to get 9090 port up - it continues in an infinite loop checking the status in function "check_switch_started" after trying to start the switch.

But if I change the thrift port as follows,
python ./behavioral-model/mininet/1sw_demo.py --behavioral-exe behavioral-model//targets/simple_switch_grpc/simple_switch_grpc --thrift-port 9559 --json p4Programs/basic.json

The topology comes up correctly:
*_** Creating network
*** Adding hosts:
h1 h2
*** Adding switches:
s1
*** Adding links:
(h1, s1) (h2, s1)
*** Configuring hosts
h1 h2
*** Starting controller

*** Starting 1 switches
s1 Starting P4 switch s1.
behavioral-model//targets/simple_switch_grpc/simple_switch_grpc -i 1@s1-eth1 -i 2@s1-eth2 --thrift-port 9559 --nanolog ipc:///tmp/bm-0-log.ipc --device-id 0 p4Programs/basic.json
P4 switch s1 has been started.

**********
h1
default interface: eth0 10.0.0.10       00:04:00:00:00:00
**********
**********
h2
default interface: eth0 10.0.1.10       00:04:00:00:00:01
**********
Ready !
*** Starting CLI:
mininet>_

I confirmed that with any port number other than 9559, the python program fails to bring up the topology. I  tried a basic TCP server program using these port numbers and they work. It has something to do with thrift it seems.

Please suggest.

**Comment by antoninbas** [comment]
I don't think this is behaving as you think it is.
Port 9559 is the reserved P4Runtime port. By default simple_switch_grpc will start a P4Runtime gRPC server on that port. The Python script you are using checks for connectivity to the port provided as an argument to `--thrift-port`: https://github.com/p4lang/behavioral-model/blob/f16d0de3486aa7fb2e1fe554aac7d237cc1adc33/mininet/p4_mininet.py#L94-L109

However, it just checks for TCP connectivity. It doesn't actually check that the port is used to run an actual bmv2 Thrift server. In your case, there is no Thrift server, but a P4Runtime gRPC server, but the connectivity check still succeeds since a TCP connection can be established.

My best guess, which could be wrong, is that you didn't actually enable Thrift support in simple_switch_grpc: https://github.com/p4lang/behavioral-model/tree/main/targets/simple_switch_grpc#enabling-the-thrift-server. Thrift is disabled by default for simple_switch_grpc.

**Comment by hkaur-hsc** [comment]
Thanks! It worked with "--with-thrift" passed to the configure options and recompiling simple_switch_grpc.

**Comment by hkaur-hsc** [comment]
Apologies for replying here and not on GitHub. Somehow, I am not able to reset my password. There is another issue I have hit.

Following are the commands used:
./mycontroller.py --p4info basicp4info.txt --bmv2-json basic.json
./behavioral-model//targets/simple_switch_grpc/simple_switch_grpc -i ***@***.*** --nanolog ipc:///tmp/bm-0-log.ipc --device-id 0 --no-p4 -- --grpc-server-addr 10.0.1.6:9009

The above commands work perfectly fine if I run the simple_switch_grpc  and the controller (which makes connection with the switch running on same address as given in grpc-server-addr) on SAME machine. I am able to write rules and read the tables with basic.json

But if the controller and simple_switch_grpc are running on different machines, then the controller code makes the switch connection and completes the Arbitration command but fails to initialize the P4 program in the switch. On running through pdb, I found that it hangs at "s1.SetForwardingPipelineConfig(p4info=p4info_helper.p4info,"

Following is the pdb snapshot:

***@***.***


Please point out any obvious mistake being done.

Best regards
Harpreet
