### ISSUE TITLE
Unexpected key field for BMV2 example

### ISSUE THREAD

**Issue by VolodymyrPeschanenkoIntel** [p4lang/behavioral-model#1126]
The [match-on-exprs2-bmv2.p4](https://github.com/p4lang/p4c/blob/main/testdata/p4_16_samples/match-on-exprs2-bmv2.p4) finished with the messages for attached stf:
```
OrderedDict([('hdr.ethernet.srcAddr[22:18]', 'exact'), ('hdr.ethernet.dstAddr & 0x10101010101', 'exact'), ('etherType_less_10', 'exact')])
Exception  Unexpected key field hdr.ethernet.dstAddr
```
[match-on-exprs2-bmv2.stf.txt](https://github.com/p4lang/behavioral-model/files/9111811/match-on-exprs2-bmv2.stf.txt)

[match-on-exprs2-bmv2-BMV2SimpleSwitchMidEnd_43_MidEndLast.p4.txt](https://github.com/p4lang/behavioral-model/files/9111814/match-on-exprs2-bmv2-BMV2.SimpleSwitchMidEnd_43_MidEndLast.p4.txt)

**Comment by VolodymyrPeschanenkoIntel** [comment]
[invalid-hdr-warnings4.json.txt](https://github.com/p4lang/behavioral-model/files/9469303/invalid-hdr-warnings4.json.txt)

**Comment by antoninbas** [comment]
The JSON file doesn't match the P4 program.

I also don't know why the issue was opened in this repository: the Python exception happens in the stf runner. Either there is an issue with the generated JSON or a bug in the stf runner. In either case, it would be a p4c issue.

Closing this for now, feel free to re-open with more context in the p4c repo.
