### ISSUE TITLE
Priority out of range, dropping packet

### ISSUE THREAD

**Issue by xhy199904** [p4lang/behavioral-model#1156]
When I use the priority queue on the p4 program, and modify the metadata and assign a value of 7 to the qid field. An error "Priority out of range, dropping packet" is reported in the log.

**Comment by xhy199904** [comment]
Need to magnify “default_nb_queues_per_port ” .Problem solved.

**Comment by tuananh01** [comment]
Do you mean changing the `default_nb_queues_per_port ` value to a number of queues we want, then recompile the switch again?

**Comment by jafingerhut** [comment]
If you compile the latest version of behavioral-model repo code and produce a simple_switch_grpc binary, if the source code is from a version of this repo dated 2022-Apr-05 or later, then you can use a command line option `--priority-queues 8` to cause the traffic manager to have 8 queues per output port, instead of the default of 1.

You _could_ change `default_nb_queues_per_port` from 1 to a different value in the source code (e.g. 8), and then recompile it.  Then the default number of queues per output port would be 8 if you _did not_ use the `--priority-queues` command line option, but if you did use the `--priority-queues` command line option, the number from that command line option would be used instead of the default of 8.

I am not sure why you would want to change the default value in the source code and recompile it, but you may do so if you wish.  It seems easier to me to simply use the `--priority-queues` command line option.

**Comment by Eternity-Wang** [comment]
When I run p4-learning multiqueue example, I also meet log error 'Priority out of range, dropping packet', what I use is simple_switch. Though I modify default_nb_queues_per_port to 8, but it still log this error.

**Comment by tuananh01** [comment]
> When I run p4-learning multiqueue example, I also meet log error 'Priority out of range, dropping packet', what I use is simple_switch. Though I modify default_nb_queues_per_port to 8, but it still log this error.

They have updated an option to simple_switch so you can now enable priority queues in the .txt switch files. You can see more details here: 
https://github.com/nsg-ethz/p4-learning/tree/master/examples/multiqueueing

**Comment by Eternity-Wang** [comment]
> > When I run p4-learning multiqueue example, I also meet log error 'Priority out of range, dropping packet', what I use is simple_switch. Though I modify default_nb_queues_per_port to 8, but it still log this error.
> 
> They have updated an option to simple_switch so you can now enable priority queues in the .txt switch files. You can see more details here: https://github.com/nsg-ethz/p4-learning/tree/master/examples/multiqueueing

Thanks for your help, I have solved this problem.
