### ISSUE TITLE
ingress_global_timestamp  does not represent correctly IAT

### ISSUE THREAD

**Issue by nhnghia** [p4lang/behavioral-model#1161]
Hi,

I create [a simple P4 router](https://github.com/mosaico-anr/p4-int-l4s/blob/main/testbed/log/log-ingress_tstamp/simple_router.p4app/simple_router.p4#L70) to be able to measure Inter Arrival Time (IAT) of packets. To do so, I use `log_msg` to print `ingress_global_timestamp` in `ingress` control:

```
        log_msg("=====ingress_global_timestamp: {}", {standard_metadata.ingress_global_timestamp});
```

Thus, the IAT between 2 consecutive packets is the interval between the two ingress_global_timestamp values.

The problem is that the IAT given by this P4 program does not represent exactly the IAT of packets arrived at the router. The following table represents the results given by (i) Wireshark which captures the arrived packets and (ii) the P4 router.

| IAT given by Wireshark | IAT given by P4 |
|---|---|
| ![IAT wireshark](https://raw.githubusercontent.com/mosaico-anr/p4-int-l4s/main/testbed/log/log-ingress_tstamp/interval-wireshark.png) |  ![IAT P4](https://raw.githubusercontent.com/mosaico-anr/p4-int-l4s/main/testbed/log/log-ingress_tstamp/interval-p4.png) |

As you can see, while the IAT given by Wireshark are stable, the ones given by P4 are randomly (?). 

Any suggestions will be appreciated!
Thank you

**Comment by jafingerhut** [comment]
Those times are measured at two different places in the system.  One is wherever WIreshark is capturing them, probably on a virtual or physical Ethernet interface.  The other is when the packet is inside of the simple_switch/simple_switch_grpc process, just before it is about to perform the ingress parser on each one.

It appears that the average interarrival time is about the same for both, so I suspect what you are seeing here is the reality of the simple_switch process reading batches of 2 or 3 packets obtained from the interface, and processing them more closely in time to each other than they arrived, because the earlier packet was waiting in some operating system buffer or queue somewhere.

**Comment by nhnghia** [comment]
Thanks @jafingerhut. 

> ... the reality of the simple_switch process reading batches of 2 or 3 packets obtained from the interface ...

Is it possible to reduce these batches to 1? (certainly compensated by performance) ?

**Comment by nhnghia** [comment]
Thanks again @jafingerhut for your time and the explanation. 

The last question: how does a BMv2 switch capture a packet at its ingress NIC? 
If I'm not wrong, BMv2 uses [libpcap](https://github.com/p4lang/behavioral-model/blob/main/src/BMI/bmi_interface.c#L134). If so, libpcap can provide the timestamp when the packet was capturing. Thus I'm thinking about exposing this timestamp in the p4 metadata.

**Comment by nhnghia** [comment]
Closed as these two timestamps are measured differently at different locations:

![](https://user-images.githubusercontent.com/3466799/205669223-48e06fcf-3009-4048-a961-132ae5661ac3.png)
