### ISSUE TITLE
How to get queue size periodically to calculate any statistical parameter like average,mean,median,variance?

### ISSUE THREAD

**Issue by padshahrohan** [p4lang/behavioral-model#1168]
We have a very simple topology as shown below.
![image](https://user-images.githubusercontent.com/22100554/206835071-df9b7abd-0542-4689-b04e-5860e73ce0a7.png)

We are using v1model architecture for the switch.

Link Bandwidths:

h1 - s1 = 50 Mbps
s1 - s2 = 0.01 Mbps
s2 - h2 = 0.02 Mbps

s1-s2 link is a bottleneck link and we can see a queue being formed when we continuously send packets from h1 to h2. We copy the enq_qdepth which is available in standard queue metadata to a register. We are able to see the instantaneous queue size from the switch CLI by reading that register value.

Now we are stuck on how to get queue size on periodic intervals so that we can calculate average queue size or any other parameter based on the dataset, does p4Lang have any provision for that?

**Comment by jfingerh** [comment]
You can do what you wish using a P4 register, e.g. one with a separate entry per queue for which you want to maintain an average queue depth.

In each element of the P4 register, you could store the following:

+ some measure of the average queue depth, A, chosen by you
+ the time T (e.g. egress_global_timestamp value) when that queue depth was observed

When you process a packet in egress, you can read the current state for the queue, and using those values plus the current time T_now and queue depth Q, calculate a new average queue depth A_now, and write the new values A_now and T_now back to the P4 register index that you read from.

It is up to you how fancy you want to get with calculating the new value A_now.  You could use an exponentially weighted moving average with a time constant C, calculated as some approximation of the following formula:

```
A_now = A + (A_now - A) * exp((T_now - T) / C)
```
or something cheaper than that.  As ideas for ways to do such a calculation in P4 with only table lookups, shifts, and add/subtract, see this article:
https://github.com/jafingerhut/p4-guide/blob/master/docs/floating-point-operations.md

Note: Tofino has a "Low Pass Filter" extern that implements a feature like the above, without a developer having to implement it all themselves, called `Lpf` here: https://github.com/barefootnetworks/Open-Tofino/blob/master/share/p4c/p4include/tofino1_base.p4#L585-L595 because calculating exponentially weighted moving averages is a fairly useful thing in high performance data planes.

**Comment by jfingerh** [comment]
By the way, if you would not mind asking your question here, I would be happy to answer it there, too.  I believe the question and answer would be easier to find later on that web site, vs. finding a closed issue on this Github repository: https://forum.p4.org

**Comment by padshahrohan** [comment]
Thanks for the reply. I have couple of questions though, currently we are send packets from h1 to h2 in a continuous loop, hence the way queue size will be seen will always be fixed, for eg: after couple of seconds of starting the send script, we observe the queue size of 20, then 60 and once queue size reaches 63 packets queue is full and packets start dropping.

This pattern is fixed, can this this be varied, like under what circumstances/scenario of traffic i can observe some varying patterns in queue size ?

Considering EWMA also if the way queue is getting populated, the average wont change right?

So how should we simulate the traffic to get different queue size? 

Yeah sure i will raise the question on the p4 forum as well.

**Comment by padshahrohan** [comment]
@jfingerh https://forum.p4.org/t/how-to-get-queue-size-periodically-to-calculate-any-statistical-parameter-like-average-mean-median-variance/565 created link to question on p4 forum org

**Comment by jfingerh** [comment]
BMv2 is NOT currently a great platform on which to simulate constant-bit-rate links between switches.  If you want to get into modifying BMv2 to become better for this purpose, look at this issue for some ideas on deficiencies today: https://github.com/p4lang/behavioral-model/issues/1067

If you want to simulate performance-accurate traffic, I would recommend using something like NS3 https://www.nsnam.org and/or creating your own simulation environment that accurately models the aspects of network performance that you want to model.
