### ISSUE TITLE
make check for simple_switch_grpc failed

### ISSUE THREAD

**Issue by zxy909** [p4lang/behavioral-model#1171]
p4@p4:~/behavioral-model/targets/simple_switch_grpc$ ./configure --with-sysrepo
p4@p4:~/behavioral-model/targets/simple_switch_grpc$ make check
...

[----------] 2 tests from SimpleSwitchGrpcTest_gNMI
[ RUN      ] SimpleSwitchGrpcTest_gNMI.PortOperStatusUpdates
test_gnmi.cpp:107: Failure
Value of: cleanup_data_tree().ok()
  Actual: false
Expected: true
[  FAILED  ] SimpleSwitchGrpcTest_gNMI.PortOperStatusUpdates (12 ms)
[ RUN      ] SimpleSwitchGrpcTest_gNMI.PortCounters
test_gnmi.cpp:107: Failure
Value of: cleanup_data_tree().ok()
  Actual: false
Expected: true
[  FAILED  ] SimpleSwitchGrpcTest_gNMI.PortCounters (10 ms)
[----------] 2 tests from SimpleSwitchGrpcTest_gNMI (23 ms total)

**Comment by jafingerhut** [comment]
I have just tried running `make check` in this same directory on each of the three operating systems listed below, and all tests passed.

+ Ubuntu 18.04
+ Ubuntu 20.04
+ Ubuntu 22.04

Then I ran the script install-p4dev-v6.sh following the instructions on this page: https://github.com/jafingerhut/p4-guide/blob/master/bin/README-install-troubleshooting.md

I would recommend that you consider starting from one of those operating systems, freshly installed, i.e. with no other software installed on them, and try using the same install-p4dev-v6.sh script to install the open source P4 development tools, and see if the tests pass for you then.

**Comment by antoninbas** [comment]
@jafingerhut I don't think you run `configure` with `--with-sysrepo` in your installation scripts.
Here, the problem seems to be specific to that scenario (simple_switch_grpc gNMI support through sysrepo).

@zxy909 It is very likely that this code is broken:
- we no longer test it in CI as far as I can tell
- it was never widely used

If you need bmv2 with proper gNMI / OpenConfig support, I recommend that you take a look at Stratum with the bmv2 backend: https://github.com/stratum/stratum
