### ISSUE TITLE
Performance issue of simple_switch_grpc

### ISSUE THREAD

**Issue by Johnny-dai-git** [p4lang/behavioral-model#1172]
HI, 

I am running some test on cloud lab bare metal machine and I encounter some performance problem while I am running the bmv2(simple_switch_grpc) instance on the metal machine.

I use the perf tool to test the throughput of the physical interface on the bare metal machine and the throughput is around 35Gb/s. However, when I run a simple p4 forwarding program with the simple_switch_grpc instance. The throughput become 24mb/s.

Is there any explanation on this situation ? Or is there anything I can do to solve such performance problem?

Best Regards,

**Comment by jafingerhut** [comment]
Have you read through this document?  https://github.com/p4lang/behavioral-model/blob/main/docs/performance.md

**Comment by jafingerhut** [comment]
I have just started from a freshly installed Ubuntu 20.04 system

I cloned this repo https://github.com/jafingerhut/p4-guide

I followed the instructions at the README link in your comment and used the `install-p4dev-v6.sh` version of the install script.

Then I ran the following commands, and it successfully cleaned and compiled again the behavioral-model code with optimization enabled:
```
cd behavioral-model
make clean
./autogen.sh
./configure 'CXXFLAGS=-g -O3' 'CFLAGS=-g -O3' --disable-logging-macros --disable-elogger --with-pi --with-thrift
make
sudo make install
sudo ldconfig
```
I ran a few simple functional tests with the simple_switch_grpc binary built by the commands above, and they all passed.

Did you try something different than the above?

If so, I would recommend trying exactly the steps above, and if you get an error, please describe exactly the steps you followed and exactly what error you got.  Saving ALL of the output of the commands above is recommended, but since the output can be quite long, uploading the file to some other place, e.g. a personal Github repo of yours, and linking to it from here, is preferable to copying and pasting many pagefuls of text into a comment.

**Comment by jafingerhut** [comment]
I have little experience with trying to achieve good performance with bmv2, or analyzing performance issues with it.

Things that you could try checking:

When you are measuring the maximum packet forwarding performance you are able to achieve with BMv2, what does `top` say is the simple_switch / simple_switch_grpc CPU utilization?  If it is less than 100% of one CPU core when forwarding from one input interface to one output interface, then something else besides the simple_switch process is likely the bottleneck, not simple_switch.  For example, perhaps something about the way packet I/O is being done is the performance bottleneck instead.

**Comment by jafingerhut** [comment]
I do not know of any reason why simple_switch and simple_switch_grpc should have any noticeable difference in their packet processing performance.  The main difference between them that I know about is that simple_switch_grpc is able to accept table updates via the P4Runtime API message-passing interface, whereas simple_switch cannot.

**Comment by jafingerhut** [comment]
No one I know of has any plans to make bmv2 a production-grade packet processing device, intended for use in production environments.  That could change tomorrow, of course, but I do not expect it to change.

The DPDK back end for P4 _is_ intended to be used in performance-sensitive situations.  It probably does not have as many optimizations as it will have a year or two from now, but it is being developed with performance in mind from day one.

**Comment by antoninbas** [comment]
@Johnny-dai-git I know you closed this issue, but I wanted to add that what you are observing (low throughput with no change even when you use the correct build flags) can sometimes be explained by checksum issues. This can be confirmed by capturing traffic with Wireshark.
The general recommendation is to 1) disable all checksum offloads on the NIC, 2) ensure that you compute the checksum correctly in P4.

**Comment by hkgb77** [comment]
Hi,

If this helps anyone --
I tried running simple_switch_grpc with two hosts
H1<->switch<->H2
the only tables my P4 program has for matching the l2 MAC address and for matching Ipv4 LPM.
I ran some tests with iperf3 and following are the results:
Without configure options suggested in this post, I see packet loss beyond 7Mbps.
With configure options changed to disable logging (as per Andy's response), I could reach 55-56 Mbps without any loss.
