### ISSUE TITLE
Can I get the index of a value in the register by custom_lib?

### ISSUE THREAD

**Issue by againwq** [p4lang/behavioral-model#1223]
I want to get the index of a value in the register，but the register object does not support this operation. Is it possible to extend operation by custom c++ lib supported by bmv2?

**Comment by antoninbas** [comment]
You can define your own extern function or object, and implement this functionality in C++. There is an example here: https://github.com/p4lang/behavioral-model/tree/main/examples/custom_extern

**Comment by againwq** [comment]
This example just show that how to manipulate basic data. If I want to do som operation in p4 register, how do I declaremy extern 
p4 function define my c++ function

**Comment by antoninbas** [comment]
From a bmv2 standpoint, you could write the following extern function:
```cpp
void register_find(bm::Data &index, const bm::RegisterArray &ra, const bm::Data &v) {
	// look for value "v" in "ra", and set "index" appropriately
}
BM_REGISTER_EXTERN_FUNCTION(register_find, bm::Data &, const bm::RegisterArray &, const bm::Data &);
```

I am not sure what the P4 declaration would look like, and I am not sure if there is full compiler support (p4c with bmv2 backend) for this. But it is worth a try. Maybe something like this:
```p4
extern void register_find<T>(inout bit<32> index, in register<T> ra, in T v);
```

If this doesn't work, you will need to define your own register extern type (instead of using the standard v1model one), with the extra method that you need. This should be a good example: https://github.com/p4lang/behavioral-model/blob/main/targets/psa_switch/externs/psa_counter.h. You will need to do a similar thing, but with `RegisterArray` instead of `CounterArray`. An important thing to keep in mind is that bmv2 only supports registers which store binary strings (`bit<X>` /  `int<X>` in P4). It doesn't support registers with an arbitrary value type (e.g. struct).
