### ISSUE TITLE
Problem using multicast in runtime

### ISSUE THREAD

**Issue by songhaoran666** [p4lang/behavioral-model#1229]
I installed BMV2 on the server, and an error occurred during the process of delivering the multicast flow table in Runtime. My command was: mc_mgrp_create 13, and the error was: thrift.Thrift.TApplicationException: TMultiplexedProcessor: Unknown service: simple_pre. Did you forget to call registerProcessor()?   Thank you.

**Comment by jafingerhut** [comment]
I have simple_switch, simple_switch_grpc, p4c, and a few other open source tools on an Ubuntu 20.04 Linux system compiled and installed by running the shell script install-p4dev-v7.sh mentioned here: https://github.com/jafingerhut/p4-guide/blob/master/bin/README-install-troubleshooting.md

When I try the steps you describe, I do not get this error.  Thus I suspect that there is at least one, and perhaps many, differences in how we installed the open source P4 development tools on our systems.

Are you able to try starting from a fresh Ubuntu 20.04 or 22.04 Linux system and try the install script above, to see if it also works for you?

If not, I am not likely to be able to help you determine how you installed the software differently, and how you might change your system so that it does work correctly.
