### ISSUE TITLE
add_header in action is not working

### ISSUE THREAD

**Issue by dannyxx001** [p4lang/behavioral-model#258]
I face a problem that `add_header` is not working in P4 program.
The following code is my simple code used to test add_header.

```
header_type test_header_t {
    fields {
        test1 : 16;
        test2 : 16;
    }
}

header test_header_t test_header;

table test_add_header_table {
    actions {
        test_add_header;
    }
    size: 1;
}

action test_add_header(port) {
    modify_field(standard_metadata.egress_spec, port);
    add_header(test_header);
    modify_field(test_header.test1, 0xAABB);
    modify_field(test_header.test2, 0xCCDD);
}

control ingress {
    apply(add_header_test_table);
}
```

I skip the parser and other header part which means I don't put the whole code here.
But I can tell that I only parse the ethernet and ipv4 packet.
And I just want to test appending a new header after the packet.
And I use wireshark to monitor the packet in mininet.
However, I don't see any new header append to the packet.
Can anyone tell me how to handle the problem? Or what's the mistake I make?
I use the latest bmv2 repository and use the simple_switch target and I don't modify the code in bmv2.
Thank you.

**Comment by jnfoster** [comment]
Hi Danny, 

It's a little hard to tell without seeing your whole program, but I strongly suspect the issue is due to the deparser. In P4-14, the deparser is automatically generated from the parser. In particular, if it doesn't parse `test_header` from some state, then it won't ever deparse it on the other side. This limitation was one of the primary motivations for adding explicit deparsers to P4-16.

As a work-around you can add a dummy state in the "right" place in the parser that is unreachable -- e.g., because the condition that guards it never evaluates to true. This should cause the deparser to emit your new header.

**Comment by dannyxx001** [comment]
OK, I see. Thank you for your reply.
Tomorrow I will try to let it appear in a dummy state.
If I get any new result, I will report here, thank you.

**Comment by antoninbas** [comment]
yes @jnfoster is right. You can easily confirm by looking at the deparser definition in the input JSON: it's a simple ordered list of headers and your header should be missing. The reason why your header needs to be in the parse graph has been discussed at length on the p4-dev mailing list: the deparser "code" is obtained by producing one topological sorting of the parse graph. This means that all the headers you want to deparse need to show up in the parse graph. We are also sometimes constrained to add dummy transitions to force the compiler to produce the "right" topological sorting for us (since the sorting is not necessarily unique).
There used to be a time when we were throwing a compiler error if a declare header was missing from the parse graph. I can't remember why we removed it, we must have run in some kind of limitation.

**Comment by dannyxx001** [comment]
It's OK. @antoninbas I think I can accept the header need to show up in parse graph.
Thank you guys. Now it's working.
Thank to tell me that the add_header need a state in parser.
