### ISSUE TITLE
test_switch failing

### ISSUE THREAD

**Issue by anirudhSK** [p4lang/behavioral-model#261]
When I run make check on a fresh installation (after make and make install), all tests pass, except for test_switch:

ubuntu@ip-172-30-0-252:~/behavioral-model/tests$ ./test_switch 
[==========] Running 9 tests from 1 test case.
[----------] Global test environment set-up.
[----------] 9 tests from Switch
[ RUN      ] Switch.GetConfig
[       OK ] Switch.GetConfig (0 ms)
[ RUN      ] Switch.ConfigOptions
[       OK ] Switch.ConfigOptions (0 ms)
[ RUN      ] Switch.GetP4Objects
[       OK ] Switch.GetP4Objects (2 ms)
[ RUN      ] Switch.SerializeState1
[       OK ] Switch.SerializeState1 (2 ms)
[ RUN      ] Switch.SerializeState2
Thrift server was started
Traceback (most recent call last):
  File "../tools/runtime_CLI.py", line 30, in <module>
    import bmpy_utils as utils
  File "/home/ubuntu/behavioral-model/tools/bmpy_utils.py", line 26, in <module>
    from thrift import Thrift
ImportError: No module named thrift
lt-test_switch: utils.cpp:55: CLIWrapperImp::~CLIWrapperImp(): Assertion `pclose(CLI_f) == 0' failed.
Aborted (core dumped)

The error suggests that the thrift python package is missing, but I installed thrift from source using the install_deps.sh script and I do see these files:
/usr/lib/python2.7/site-packages/thrift/Thrift.py
/usr/lib/python2.7/site-packages/thrift/Thrift.pyc
/usr/lib/python2.7/site-packages/thrift/Thrift.pyo
I can also run the command thrift from the command line.

**Comment by antoninbas** [comment]
Hi Anirudh,
The `Thrift.py` is installed in the same place on my machine. You may want to try running `from thrift import Thrift` in a Python console to confirm that it is failing.
It could be an issue with your `PYTHONPATH`, even though there is no reason for the files to be installed there if it's not in the `PYTHONPATH` to start with. You can try importing other packages under `/usr/lib/python2.7/site-packages/` to check if it works.
The most common issue I see is the Thrift `configure` script "deciding" that it is not going to install the Python package by default, but that doesn't seem to be the case here. You could always try specifically re-installing the Python package with `pip`, but you would have to make sure that the version matches the C++ library version.
In any case, I am pretty sure this is not related to the test code. If you don't need the Thrift Python package, you can just ignore this, but you won't be able to run the runtime CLI.
I'm leaving this issue open in case someone can help. Please let us know if you find the root cause.

**Comment by antoninbas** [comment]
You may also want to make sure that `/usr/lib/python2.7/site-packages/thrift/__init__.py` exists, but I don't see why it wouldn't...

**Comment by anirudhSK** [comment]
Thanks for the PYTHONPATH suggestion. /usr/lib/python2.7/site-packages wasn't in sys.path. I fixed it by adding export PYTHONPATH=/usr/lib/python2.7/site-packages to ~/.bashrc as suggested here:
http://daily-hacking.blogspot.com/2009/07/installed-python-module-thrift-not.html

This doesn't seem too hygienic though. I wonder why this problem hasn't happened before because Ubuntu apparently doesn't include site-packages on its sys.path by default.  But I am closing this for now (https://leemendelowitz.github.io/blog/how-does-python-find-packages.html)
