### ISSUE TITLE
P4_16 version of simple_router.p4 does not work in mininet

### ISSUE THREAD

**Issue by vikramnathan** [p4lang/behavioral-model#272]
I am running both the following on mininet using simple_switch (both p4s and jsons attached):
1) behavioral-model/mininet/simple_router.json (compiled from P4-14)
[simple_router.json.txt](https://github.com/p4lang/behavioral-model/files/718148/simple_router.json.txt)
[simple_router.p4.txt](https://github.com/p4lang/behavioral-model/files/718147/simple_router.p4.txt)
2) p4c/testdata/p4_14_samples_output/simple_router.json (P4-16, translated from the P4-14 source used for (1)), modified to run on simple_switch, as described here: http://lists.p4.org/pipermail/p4-dev_lists.p4.org/2016-May/000329.html.
[simple_router16.json.txt](https://github.com/p4lang/behavioral-model/files/718150/simple_router16.json.txt)
[simple_router16.p4.txt](https://github.com/p4lang/behavioral-model/files/718151/simple_router16.p4.txt)

For both, I run 1sw_demo.sh with 2 hosts and run the CLI commands in behavioral-model/mininet/stress_test_commands.txt. This also verifies that both switches are up and running.

For (1), I am able to successfully ping between hosts: `h1 ping h2`
For (2), no replies are received for the ping.

It seems like the P4-16 version of the simple_switch program does not work on mininet.

**Comment by antoninbas** [comment]
2 is working fine for me
I simply compiled simple_router.p4 (the checked-in version): `p4c-bm2-ss simple_router.p4 --p4-14 -o simple_router.json` and used it with `1sw_demo.py`. I am attaching the json file which is produced in my case.
[simple_router.json.txt](https://github.com/p4lang/behavioral-model/files/718196/simple_router.json.txt)

You may want to try with my json and see if it works for you too. If it does work you may be using an old version of `p4c-bm2-ss`.

Note that it is no longer necessary to edit simple_router.p4 for simple_switch. I recently modified the simple_router target to behave more like simple_switch as it was a source of confusion for people (https://github.com/p4lang/behavioral-model/pull/264). So the p4-dev email you are pointing to is no longer relevant.

It's difficult to compare the 2 json files (yours and mine) because small changes in the p4c compiler can cause big variations in the json.

**Comment by vikramnathan** [comment]
Your json file works for me too.

If I'm not mistaken, it looks like the simple_router.p4 source that you compiled is written in P4-14. Is there an example of a P4-16 program that works with mininet? We're trying to debug a P4-16 program in mininet, and it would be extremely useful to have a working program to compare against.

Leaving this bug open just to get an answer to the above question, but otherwise, you can close it. Thanks!

**Comment by antoninbas** [comment]
I'll try with your P4_16 program today

**Comment by antoninbas** [comment]
After investigating this, I believe that the checksum definition in the JSON for the IPv4 checksum is wrong. It is not writing the checksum result to a temporary metadata field, and not to the header field. Commenting out the line which decrements the TTL solves the issue (the IPv4 header is no longer modified so the checksum does not need to be recomputed and the packet is not dropped by the kernel). I'll close this issue since it is a problem with the compiler-generated JSON input.

**Comment by vikramnathan** [comment]
Yep commenting out the TTL modification line seems to do the trick. Thanks!
