### ISSUE TITLE
Question: Does the p4ofagent support the bmv2? 

### ISSUE THREAD

**Issue by Wasdns** [p4lang/behavioral-model#294]
Hi, all!

I'm sorry to bother you. Recently, I'm trying to start the mininet topo that consists of many P4 switches and hosts. And I want to use the openflow controller to control the P4 switches. I read the [readme](https://github.com/p4lang/p4ofagent#p4-openflow-agent) of the repo p4ofagent and found that the environment it used was p4factory. Does the p4ofagent support the bmv2? BTW, the readme refered `The Mapping File`, I don't understand how it writes(is that file? [l2.py](https://github.com/p4lang/p4factory/blob/master/targets/l2_switch/openflow_mapping/l2.py)). If the p4ofagent support the bmv2, how can I get start with it? The same way in the readme? 

Thank you! :)

**Comment by antoninbas** [comment]
This has been covered quite a few times on the p4-dev mailing list, so you should probably browse that:
- http://lists.p4.org/pipermail/p4-dev_lists.p4.org/2017-January/000641.html
- http://lists.p4.org/pipermail/p4-dev_lists.p4.org/2016-November/000587.html
- ...
This is not a very straightforward process, so you may have to get your hands dirty. In any case I am closing this issue, because it is not directly related to bmv2. If you need more help, I suggest you open an issue with p4ofagent.
