### ISSUE TITLE
Queue information in ingress

### ISSUE THREAD

**Issue by voinescuandrei** [p4lang/behavioral-model#310]
Hi!

I am writing a P4 program that needs queue data for the priority queues like the ones in simple_switch. Is there any way of obtaining this information in the ingress pipeline? I would like to assign priorities based on that information.

Also, is "queueing_metadata" part of the standard? Can I expect this to be widespread in hardware P4 devices?

Thanks,

Andrei

**Comment by antoninbas** [comment]
Hi,

I don't understand your question. You can't access queueing information in the ingress pipeline, because the ingress pipeline happens before the queueing. By definition the queueing is between the ingress and egress pipelines.
You can expect this information to be widespread across devices, but potentially with different names.

**Comment by voinescuandrei** [comment]
Sorry,  I meant to say queue depth. Let's say I have two priority-based queues for a single egress port that I have chosen for a packet. I would like to make a priority decision based on the depth of both.

**Comment by antoninbas** [comment]
It's not possible with bmv2 simple_switch and I am not sure it is realistic for many hardware targets. I am not sure you can access queue depth for packet processing until the packet has visited the queue.

**Comment by voinescuandrei** [comment]
The simplest solution would be for me to add an intrinsic_metadata that gets populated with all the queue depths when I enter the ingress pipeline, but this is both not elegant and too far from the reference implementation. 

Perhaps I can achieve this by recirculating the packet with the additional queueing data? I see in the specification that resubmission should put the packet back in the parser, while in the bmv2 it is resubmitted to the input buffer, so it has to wait for other packets. Which one of these is the reference design for the recirculate primitive?

Thanks!

**Comment by antoninbas** [comment]
I personally don't think recirculate is an elegant way to achieve this. Additionally even recirculate may not be available to all hardware targets.
When you want to have access to very specific information like this, it usually means you have a potential P4 hardware target in mind that would give you access to this information in the way you want. If this is the case it is better for you to write your own bmv2 target that emulates the hardware target as best as possible. simple_switch can be a starting point for your target.
If you are not evaluating P4 programs for some specific hardware, and this is just for the sake of experimenting with the language, you should really do what's easiest for you. There are a huge number of ways of doing what you want:
- The intrinsic_metadata solution you are proposing
- You could define a `register` in the P4 program and write queue occupancies to it, so that they are accessible to the datapath. You maybe able to use `Switch::register_write` (https://github.com/p4lang/behavioral-model/blob/master/include/bm/bm_sim/switch.h#L687).
- You could simply use your own queueing mechanism instead of the one included with bmv2 and make the queueing decision there instead of the pipeline (but then the decision is not expressed in P4...)

**Comment by qq995002966** [comment]
@voinescuandrei 
hi,voinescuandrei 
I'm doing almost the same things as you,but I how no idea to start my experiment because of the lack of the information about queue.So,If it possible could you please show me how your p4 src and Makefile look like?
John

**Comment by qq995002966** [comment]
**I have solved my problem ,not voinescuandrei's problem.** It seems that there is no relative information about queue state within `p4-spec` , but I found some useful information at mail list and get queue state successfully.
1. add follow code to your p4 program
```
header_type queueing_metadata_t {
    fields {
        enq_timestamp: 48;

        enq_qdepth: 16;

        deq_timedelta: 32;

        deq_qdepth: 16;

    }
}

metadata queueing_metadata_t queueing_metadata;
```

> It is important to understand that these metadata fields are specific to the `simple_switch` target, they are not standardized by P4. bmv2 will detect that they are defined in the P4 program and leverage them.

2. read queueing_metadata at egress phase.
