### ISSUE TITLE
continue the previous question

### ISSUE THREAD

**Issue by realmanhw** [p4lang/behavioral-model#328]
OK, this is my p4program, it is a function test for pushing instances.
[my p4 program.zip](https://github.com/p4lang/behavioral-model/files/908051/my.p4.program.zip)
my problem is described in the previous issue. 
if you want to run it , modify`env.sh` first, then run `./compile_bmv2`, then run `./topology.py`
you can open a new terminal and run` ./send_cmd.sh` to publish flowtable
the packet is defined in `click packet`, you should send it by **Click**(if you used it before), 
when running   `./topology.py`, run` xterm h2 s1`, and in `h2` use **Click** to send the packet and you can run` wireshark `in `s1` to watch the packet.
if you can not run my p4 program well, just have a look at my p4 language code in `BorderRouting`.

**Comment by antoninbas** [comment]
One possible error is that you set the `total_length` field in your `color` header to 100, when I believe it should be 96. That would explain why you are running out of data to parse.

More importantly I don't think you understand how this space works. We are not here to debug your P4 programs & applications for you. If you believe that you found a bug in bmv2 or in the compiler, please by all means open an issue to report it, but provide a **small** P4 program and make sure we can reproduce the issue by running a single switch and with a small amount of CLI commands.
At this stage, and even though I am sure there are still quite a few bugs in bmv2 (some of which I am aware of), it is way more likely that the issue is with your code.
Similarly, if you need help to understand how bmv2 works or to achieve something in P4 / with bmv2, we would be very happy to be of assistance. But obviously that's not what you are asking for here...
The title of this issue is also close to useless; please next time show some some respect to the people answering your questions and pick a decent title. The reason why I closed your previous issue was because things were getting off-track and we had started to diverge from your original question. That was not done out of spite.

**Comment by realmanhw** [comment]
I'm sorry for making you feel uncomfortable. In the bottom of my heart, I am very grateful to you and your help to me. But maybe because I could not express myself well. I never thought about you were out of spite, I just open a new issue and upload my program to you and explain how to run it. If there's anything to make you feel uncomfortable, I say sorry to you again, Sincerely. And if you deel disturbed, you can ignore my question and close it at any time.

**Comment by realmanhw** [comment]
I'm sorry for making you feel uncomfortable. In the bottom of my heart, I am very grateful to you and your help to me. But maybe because I could not express myself well. I never thought about you were out of spite, I just open a new issue and upload my program to you and explain how to run it. If there's anything to make you feel uncomfortable, I say sorry to you again, Sincerely. And if you deel disturbed, you can ignore my question and close it at any time.
