### ISSUE TITLE
the behaviour of table lookup

### ISSUE THREAD

**Issue by ali64Mon** [p4lang/behavioral-model#353]
Hi all,

I was wondering if you could give us some clarification about how table lookup is implemented in bmv2.

I can see in the produced JSON file that each table has a match-type based on the match-type of its key fields. So, for example if a table has filed with 3 different match-types (EXACT, TERNARY, RANGE) the table match-type would be RANGE. right?

Are different lookup methods used for each key match-type in the table when applying the table on a packet? or one lookup method, based on the table's match-type, is applied to packets?

Regards,
Alireza

**Comment by antoninbas** [comment]
Based on the match type of all the fields including in the table's match key, we generate a match type for the table according to the following rules (from high priority to low priority):
- there cannot be more than one LPM field in the table
- if there is at least one range field, then the table type is range
- if there is at least on ternary field, then the table type if ternary
- if there is one LPM field, then the table type is LPM
- otherwise the table type is exact

The table match type dictates which table implementation is used by bmv2:
- if the table type is exact, we use a hash map
- if the table type is LPM, we use a trie-like data structure
- if the table type is ternary, we do a linear search. For each entry, we apply the appropriate mask to the lookup key and compare it to the stored key.
- if the table type is range, we also do a linear search. For each entry, we first check the range match fields. If it's a match, we then check the rest of the match fields using a ternary lookup.

Note that for range and ternary tables types, we now have a flow cache to avoid the linear search as much as possible.

**Comment by ali64Mon** [comment]
@antoninbas Thanks for clarification.
