### ISSUE TITLE
Question about FCS computation in simple_switch

### ISSUE THREAD

**Issue by technobilly** [p4lang/behavioral-model#389]
Hi, I wrote a few simple P4_16 programs and ran them using simple_switch. For example, I did MPLS label stripping. The output was as expected (labels removed, rest of payload as expected) but for some reason the Ethernet FCS does not get updated as revealed in Wireshark. This was true for some other header stripping experiments as well. Is there some special mechanism to invoke FCS updates or is it supposed to be automatic? As a cross-check I ran tutorials/P4d2/examples/ipv4_forward and the packets coming out from that also have bad FCS per Wireshark. What am I missing? Thanks.

**Comment by antoninbas** [comment]
We consider that computing the Ethernet FCS is out-of-scope of bmv2 and assume that the NIC will compute it.
For tutorials etc. we rely on veth interfaces create by the Linux kernel. These are purely software interfaces and I wouldn't be surprised if Linux didn't compute the Ethernet FCS for them. If you plug bmv2 to actual physical NICs, I am sure it will be computed correctly by the hardware.
BTW, rather than having a "bad FCS", I am pretty sure the packets would have no FCS at all for veth pairs.

**Comment by technobilly** [comment]
Antonin, thanks for clarifying this!
