### ISSUE TITLE
integrating simple router with Mininet

### ISSUE THREAD

**Issue by Safaamahrach** [p4lang/behavioral-model#428]
Hello,
I’m following your guide <https://github.com/p4lang/behavioral-model> to get the simple_router.p4 example running on Mininet but the hosts cannot ping each other.

I took these steps:

1) in bmv2/targets/simple_router I created the JSON: "p4c-bm --json simple_router.json simple_router.p4”
2) in bmv2/targets/simple_switch I started the switch with : “sudo simple_switch -i 0@eth0 -i 1@eth1 ../simple_router/simple_router.json”
and I see successful starting:

Thrift port was not specified, will use 9090
Adding interface eth0 as port 0
Adding interface eth1 as port 1
Thrift server was started

3) In bmv2/mininet I started the python 1sw demo: "sudo python 1sw_demo.py --behavioral-exe ../targets/simple_router/simple_router --json ../targets/simple_router/simple_router.json”

I see the program starting.

4) Finally I populate the tables In bmv/targets/simple_router by running “./runtime_CLI --json simple_router.json < commands.txt”

I see that all entries are added with a message “entry has been added with handle x”.

5) I do a pingall and it fails. I checked with wireshark that when I do a “h1 ping h2”, the switch receives packets at eth1 but nothing shows up at eth2 of switch, seemingly dropping the packets.

**Comment by antoninbas** [comment]
There is no need for your step 2, don't know why you would try starting a separate instance of the switch. What probably happens is that Mininet fails to start the switch in step 3 because you already started one manually and TCP port 9090 is already taken as a result. If you use a recent version of this repo, you should be getting an error message though...
Anyway, you probably want to try again without step 2.

**Comment by Safaamahrach** [comment]
Yes It s done thank you so much
