### ISSUE TITLE
Question: Intended for table with action_selector to have entries 'pointing at' members directly?

### ISSUE THREAD

**Issue by jafingerhut** [p4lang/behavioral-model#438]
This example P4_16 program: https://github.com/jafingerhut/p4-guide/blob/master/action-profile-and-selector/action-selector.p4

has a table named 't2' with implementation = action_selector(...), here: https://github.com/jafingerhut/p4-guide/blob/master/action-profile-and-selector/action-selector.p4#L119-L131

I expect that I can create members in the action profile using simple_switch_CLI, and create groups, add members to the groups, and use the command table_indirect_add_with_group to add table entries that 'point to' that group, and that all works in my testing.

I was slightly surprised to learn that I can also create just a member, and use the command table_indirect_add to add table entries that 'point to' a member directly, without going through a group.  You can also have different table entries where some 'point to' groups, and others to members, at the same time.  See this transcript of simple_switch_CLI commands and output here, for example: https://github.com/jafingerhut/p4-guide/blob/master/action-profile-and-selector/README-selector.md

Is this behavior by design?  A bug in simple_switch?  An accident of the current implementation?

**Comment by antoninbas** [comment]
That's by design. That's why you have plain `add` and `add_with_group`. It's just for convenience really. This way you don't have to create a group with a single member, if you do not want any hashing to happen for these table entries.
You can create a member, add it to a bunch of groups,  and have some entries pointing at these groups while others point at the member directly. But the following have exactly the same semantics:
1. create member M1, create group G1, add M1 to G1, point entry E1 to G1
2. create member M1, point entry E1 to G1
Of course, in the first case, I can add some additional members to G1 and then the behavior is not the same any more.

**Comment by jafingerhut** [comment]
Thanks, @antoninbas.  I assume that this feature is expected to be preserved in the PSA specification of action_selector(), unless you believe it should not.

**Comment by antoninbas** [comment]
I believe it should remain.
