### ISSUE TITLE
Error when adding counter in simple_router.p4

### ISSUE THREAD

**Issue by Safaamahrach** [p4lang/behavioral-model#447]
Hello,
I 'm working with simple_router target and I want to add counter in simple_router.p4 to count packets from each source.  for that I add the code bellow simple_router.p4
```
counter ip_src_counter {
    type: packets;
    static: count_table;
    instance_count: 1024;
}
action count_action(idx) {
    count(ip_src_counter, idx);
}
table count_table {
    reads {
        ipv4.srcAddr : lpm;
    }
    actions {
        count_action;
        _drop;
    }
    size : 1024;
}
```
and I call     Apply (count_table);      in control ingress
Then I compile it , OK
When I want launch the topology with mininet
 sudo python 1sw_demo.py --behavioral-exe ../targets/simple_router/simple_router --json ../targets/simple_router/simple_router.json
I get Error P4 switch did not start correctly
![p4 switch did not start correctly](https://user-images.githubusercontent.com/31244674/30870963-30e0146c-a2dd-11e7-85ca-336fc90e6723.png)

**Comment by antoninbas** [comment]
Please attach your P4 program and the generated JSON file.

**Comment by Safaamahrach** [comment]
Please find attached P4 and Json files  that I use. I make them in text format to be able to import them.

[simple_router.json.txt](https://github.com/p4lang/behavioral-model/files/1335232/simple_router.json.txt)
[simple_router.P4.txt](https://github.com/p4lang/behavioral-model/files/1335233/simple_router.P4.txt)
Thank you for your help

**Comment by antoninbas** [comment]
I was able to reproduce the issue. When trying to run the simple_router binary with the JSON file you provided, I get the following error: "Unknown primitive action: count".
The simple_router target is just a toy target. It is here to demonstrate how different switch architectures can be implemented with bmv2. It doesn't support counters. If you want to use counters, please use simple_switch. Because simple_router is merely a subset of simple_switch, you may be able to get it to work by simply changing the `--behavioral-model` command-line option to use the simple_switch binary instead of the simple_router one.

**Comment by Safaamahrach** [comment]
THanks lot for your interest and help
