### ISSUE TITLE
empty `register_arrays` lead bmv2 quit unexpectedly.

### ISSUE THREAD

**Issue by qin-nz** [p4lang/behavioral-model#492]
I use latest version of simple_switch and I got an error.
```
sudo ../behavioral-model/targets/simple_switch/simple_switch -i 1@veth1 -i 2@veth2 -i 3@veth6 --pcap --thrift-port 9090 --nanolog ipc:///tmp/bm-0-log.ipc --device-id 0 ./build/mapswitch.p4.json --log-console -L trace
```
error:
```
Calling target program-options parser
terminate called after throwing an instance of 'std::out_of_range'
  what():  _Map_base::at
Aborted (core dumped)

```

**Comment by qin-nz** [comment]
Here is my json file.
[mapswitch.zip](https://github.com/p4lang/behavioral-model/files/1550344/mapswitch.zip)

**Comment by jafingerhut** [comment]
I don't have an explanation for why simple_switch is crashing with this bmv2 JSON file, but in the past when I've seen such issues, it is often because the P4 compiler was generating JSON files that simple_switch was not documented to handle, and the resolution was that the P4 compiler needed a fix.  If that is the case here, having the P4 source code for this program would be helpful.  Is a P4 program that causes this issue something you are able to share in public?

**Comment by jafingerhut** [comment]
I ran simple_switch in gdb (gdb backtrace output below) with this JSON file.  I believe it is crashing while reading the JSON file because the "register_arrays" key in the JSON file has no registers in it (just the empty list []), but there are multiple read and write operations being done on registers in the P4 program actions.  Definitely looks like a bug in the P4 compiler, producing a wrong JSON file.

**Comment by jafingerhut** [comment]
If you can update to the latest version of p4c, rebuild it, and recompile your P4_16 program with that latest version, and you still get this problem with simple_switch, please attach your P4_16 source code (if sharable) to a new issue for the project https://github.com/p4lang/p4c

**Comment by antoninbas** [comment]
Leaving this issue open for now, as the bmv2 JSON parser code should print an error message instead.

**Comment by antoninbas** [comment]
This issue has been fixed in the p4c compiler.
I also added a check (#516) in the JSON parsing code.
