### ISSUE TITLE
Always be Zero(0) - standard_metadata's (enq_qdepth) (deq_qdepth)

### ISSUE THREAD

**Issue by MaoJianwei** [p4lang/behavioral-model#493]
Hi, 

I got a problem, wish your help, thanks!

In P4-16, egress control's _apply{}_

directly do this:
```
hdr.maoTelemetryLabels[0].queue_length_in = standard_metadata.enq_qdepth;
hdr.maoTelemetryLabels[0].queue_length_out = standard_metadata.deq_qdepth;
```

The bmv2 log is in the first picture below, I can see it actually reads the **_enq_qdepth_** and **_deq_qdepth_** to hdr.maoTelemetryLabels

But, in the second picture below, we can see the corresponding **_queue_length_in_** and **_queue_length_out_** is always zero (0).

![image](https://user-images.githubusercontent.com/12800168/33884171-a26a0308-df79-11e7-93e3-676f2b5a875f.png)

![image](https://user-images.githubusercontent.com/12800168/33883693-af648e54-df77-11e7-83c6-990ee3539194.png)

**Comment by MaoJianwei** [comment]
I capture the telemetry packets by wireshark, and I'm sure both enq_qdepth and deq_qdepth in the packets are zero.
Maybe it is a bug of BMv2?

**Comment by antoninbas** [comment]
How are you creating congestion? Try setting the queue rate to something smaller than the ingress packet rate with the `set_queue_rate` (https://github.com/p4lang/behavioral-model/blob/master/targets/simple_switch/sswitch_CLI.py#L50) CLI command.
There are several things to take into account if you want to observe something:
- if your packet arrival rate is greater than what the bmv2 ingress pipeline can process, packets will be dropped before ingress, and there will be no queue buildup
- if your queue rate is not bounded, you will not observe a queue build-up either, since the egress pipeline is usually faster than the ingress one in bmv2
I don't know the performance of bmv2 on your machine for your specific program, but given that you have enabled logging, you need to use some very conservative numbers. Try the following:
- arrival rate of 100 packets per second
- queue rate of 40 packets per second
You should observe a queue buildup and eventually packet drops.

This was assuming that you were not using regular TCP traffic and that you could control the rate of the sender. If you cannot control the rate of the sender, you need to set the max bandwidth of the link, which is easy to do with Mininet for example.

**Comment by MaoJianwei** [comment]
Thanks a lot! I will try to set the queue rate today 😄 

BTW, could you please tell me, in bmv2, dose it start one thread for one switch port?

If I generate some traffic from several input port to one output port, while I don't set the queue_rate and link_max_bandwidth, can I observe a non-zero queue_len value?(will the packets be queued?)

**Comment by antoninbas** [comment]
The only guarantees are that all packets with the same ingress port are processed by the same ingress thread and that all packets with the same egress port are processed by the same egress thread. This is necessary to avoid packet re-ordering.

If you want to observe a queue build-up consistently you will have to set the queue rate.

**Comment by MaoJianwei** [comment]
Is the queue actually the queue of linux TC, or a queue data-structure in BMv2?

**Comment by MaoJianwei** [comment]
Thank you so much, I got the result.

![image](https://user-images.githubusercontent.com/12800168/33917753-ec23dc46-dfea-11e7-9206-b43b596b7fd6.png)

**Comment by antoninbas** [comment]
Glad it solved your issue.
simple_switch uses a custom C++ queue implementation which is part of the bmv2 library, as you can tell by looking at simple_switch's implementation: https://github.com/p4lang/behavioral-model/blob/master/targets/simple_switch/simple_switch.cpp#L258

**Comment by MaoJianwei** [comment]
Thanks, I will take a look 😄
