### ISSUE TITLE
Does bmv2 check the link is available before transmitting packets?

### ISSUE THREAD

**Issue by George0112** [p4lang/behavioral-model#583]
Hi, 
I'm now running an experiment which is observing the queue depth to decide if we should drop the packet in limited-bandwidth mininet. We limit the bandwidth of mininet using following code
`h1 = net.addHost( 'h1' )
    h2 = net.addHost( 'h2' )
    s1 = net.addSwitch( 's1' )
    link1 = net.addLink( h1, s1, cls=TCLink )
    net.addLink( h2, s1 )
    net.start()

    # flush out latency from reactive forwarding delay
    net.pingAll()

    info( '\n*** Configuring one intf with bandwidth of 5 Mb\n' )
    link1.intf1.config( bw=5 )
`
To my knowledge, egress_buffer should always be 0 if we didn't shrink the queue_rate (which can be limited by `set_queue_rate`). Therefore, we slightly edit simple_switch.cpp with following code.
`phv->get_field("head_queue.qdepth").set(output_buffer.size());`

We hope that we can use the information of output_buffer.size() in egress pipeline. Then we can drop some packets if the queue depth is more than a threshold. However, even we increase the size of output_buffer (definitely enough to store all our packets), we still drop some packets that we don't expect to drop. We guess that the function to transmit the packet in bmv2 doesn't check if the interface is available. 

Could anyone give us some advices or point out our mistakes?

Any suggestion will be fully appreciated. Thanks.

**Comment by antoninbas** [comment]
Your experiment doesn't make much sense IMO. The `output_buffer` queue in simple_switch has no real physical meaning. It is just used for communication between the "egress thread" which is in charge of egress processing and the "transmit thread" which is in charge of writing the packets to the outgoing interface. Doing IO in a separate thread is just a design choice I made, and I would agree that introducing one more queue in the system is not really optimal. I could just as easily have chosen to do IO in the "egress thread", just after egress processing, instead of adding the packet to the `output_buffer` queue.

On the other hand, the `egress_buffers` queues do try to be representative of what happens in a traditional ASIC, where packet buffering happens between ingress and egress.

Regarding your question, I am not exactly sure what you mean by "bmv2 doesn't check if the interface is available". bmv2 will simply call the `send` system call. If the link bandwidth you set with Mininet for the egress link is less than the rate at which bmv2 is processing packets (which seems likely since you are using a 5Mbps link), the interface queue will fill up and I would expect the packets to be dropped (silently). Putting it differently: the `output_buffer` queue is not rate-limited and packets will be sent to the interface "as fast as possible"; if the interface link cannot keep-up, the interface will drop packets. I would expect the `output_buffer` to stay pretty much empty in this scenario, but maybe you can check yourself.

The right way to do rate-limiting with bmv2 is by setting the rate for the `egress_buffers` queues.

**Comment by antoninbas** [comment]
Closing this since no update on thread; feel free to re-open if you have further questions.
