### ISSUE TITLE
Egress timestamp is not updated while transmitting the packet.

### ISSUE THREAD

**Issue by Krishnadevsinh** [p4lang/behavioral-model#632]
While debugging the P4 file using the p4dbg.py, it has been observed that the **standard_metadata.egress_global_timestamp** metadata is not being updated in BMv2 model unlike the ingress timestamp. Even we have verified that by storing this value in packet and validate that packet on egress port. So please suggest how to find the egress timestamp? 

Below is the p4dbg captured value for the reference:

P4DBG: p standard_metadata.ingress_global_timestamp
Packet id not specified, assuming current packet (25.0)
00:00:38:15:c6:bc (940951228)

P4DBG: p standard_metadata.egress_global_timestamp
Packet id not specified, assuming current packet (25.0)
00:00:00:00:00:00 (0)

Thank you.
Krishnadevsinh Gohil

**Comment by geekyprats** [comment]
I think from BMv2 perspective, egress timestamp may not be helpful for now, since that will be a part of transmit queue post deparser block, & we may have no way to use it, since metadata cannot be carry forwarded on paths.

However in real-time, hardware may have the capability to update egress timestamp where this may come handy. 
But for now, since we use software switch, I think egress timestamp may not be relevant.

Someone, please correct if this assumption is incorrect.

**Comment by antoninbas** [comment]
The `egress_timestamp` in the PSA specification is defined as

> Time that packet began processing in EgressParser

`standard_metadata.egress_global_timestamp` was added to v1model for consistency with PSA (https://github.com/p4lang/p4c/commit/eeb7b74e3d96bcaa2e18564335f7e9459c376af2) so I think the definition should be the same. Given that, I believe it makes sense to add support for it in simple_switch, so I'll open a patch for it.

**Comment by geekyprats** [comment]
@antoninbas  Thanks its working
