### ISSUE TITLE
libjudy

### ISSUE THREAD

**Issue by rdhillbb** [p4lang/behavioral-model#635]
I am trying to build behavioural-model.
I get the following message:
checking for Judy1Next in -lJudy... no
configure: error: Missing libJudy

I am using Ubuntu 16.04 LTS

**Comment by jafingerhut** [comment]
It appears that perhaps you did not install the libjudy dependency.

Look in the README for p4lang/behavioral-model, the section labeled "Dependencies", in particular this sentence: "To make your life easier, we provide the install_deps.sh script, which will install all the dependencies needed on Ubuntu 14.04."

If you want to make your life even easier, and want to install behavioral-model and also the p4c compiler, you could run this shell script on your system: https://github.com/jafingerhut/p4-guide/blob/master/bin/install-p4dev.sh

**Comment by rdhillbb** [comment]
Thank you. I think my trouble has been I installed Unbuntu 18.04.

Thank you again.

**Comment by jafingerhut** [comment]
Ubuntu 16.04 is the easier path right now.  I have had success installing p4lang/behavioral-model and p4lang/p4c on Ubuntu 18.04 (and also 16.04) with only a small change (installing Thrift version 0.11.0 instead of 0.9.2), which this script will do for you: https://github.com/jafingerhut/p4-guide/blob/master/bin/install-p4dev-with-thrift-0.11.0.sh
