### ISSUE TITLE
packet drop seen in L3 forwarding test case

### ISSUE THREAD

**Issue by dproc** [p4lang/behavioral-model#680]
Hi Experts,

When testing basic IP forwarding with model, I met below problem. 
**Topo:**
Ptf sender —— (dev_port 0 on fp0)model(dev_port 4 on fp4) —— ptf receiver

**Case:**
Ptf sender generate and transmit (5.5.5.2 -> 6.6.6.2) IP packet. 
The model has been programed to forward such traffic(routes, neighbors etc has been programmed correctly)
I send 10 packets  and expect receive all the 10.

**symptom:**
From time to time the receiver only saw 7 or 8 packets. Some packets were dropped in between.

Some preliminary analysis:
I did packet capture on interface which dev_port is bound to, I confirmed that the input dev_port fp0 received 10 packet always, but the output dev_port fp4 only send out 7 or 8 packets from time to time. 
So I think it should be the model who dropped the packets. 

The attached file "console_stdout" is the raw console output in the case where receiver only see 8 of the 10 packets. 
The attached file "console_stdout.out" is parsed from console_stdout and only focus on the packet processing part. 
I saw the ingress thread only process 8 packets in this case, which mean the 2 missing ones are dropped even before being handed over to ingress thread.

Do you have any idea about the reason of packet drop? Could it be because buffer overflow or something? 
Or Is there any method to further debug the issue? 
Thanks!
[console_stdout.zip](https://github.com/p4lang/behavioral-model/files/2535323/console_stdout.zip)
[console_stdout.out.zip](https://github.com/p4lang/behavioral-model/files/2535324/console_stdout.out.zip)

**Comment by jafingerhut** [comment]
If the missing packets are dropped before being handed over to ingress, why do you suspect that the simple_switch process is responsible?

What kinds of interfaces/connections are 'dev_port 0 on fp0' and 'dev_port 4 on fp4'?  If they are Linux virtual Ethernet interfaces, how did you create and configure them?

**Comment by antoninbas** [comment]
@dproc the logs you shared are for a proprietary bmv2 target implementation, not for one of the open-source targets (simple_switch, PSA_switch). I will close this issue. Please feel free to open a new issue if you observe the same thing with simple_switch, providing the bmv2 JSON input & the PTF script. I'm also taking the liberty to remove the attachments from your issue.

In general there is little chance to overrun bmv2 with a PTF test, since I believe PTF sends packet fairly slowly. There is also little chance to drop packets when sending a burst of ~10 packets, internal bmv2 queues are usually much larger than that and assuming the model doesn't read from the virtual interface fast enough, shouldn't packets be buffered there as well?

I noted something strange with your logs BTW: some packets have duplicate packet ids.
