### ISSUE TITLE
Logging/Printing user-defined messages

### ISSUE THREAD

**Issue by endrigoshi** [p4lang/behavioral-model#687]
Hi all!
Is it possible with p4_16 to log user-defined messages that are later printed in terminal using `--log-console` option?
Normally I am assuming that this is not possible but just in case I am asking to be completely sure about it.

**Comment by jafingerhut** [comment]
I think such a thing would be a very useful addition to the language, even if it is only for debugging programs on software switches like simple_switch.

At the moment, a slightly more verbose alternative is to use a 'debug table', which is simply a table with `actions = { NoAction; }` and `const default_action = NoAction;`.  Put in the key all header and/or metadata fields that you want to see the value of at a particular point in the program's execution, and then `apply` that table at that point in the program.  The values of all of those fields will show up in the console log when execution reaches that point.

**Comment by antoninbas** [comment]
If an extern is added to v1model to log user messages, it would be pretty straightforward to implement it for bmv2 simple _switch and redirect messages to the console logs ... assuming that this extern only supports logging plain string messages or single values.

```
extern void log_msg(in string msg);
extern void log_value<T>(in string msg, in T v);
```

Of course the P4_16 language would need to expose a string literal type for the above to work.

Having more general support like in the fmt library (https://github.com/fmtlib/fmt) would be awesome, but that couldn't be done with existing bmv2 capabilities because bmv2 doesn't support variadic externs functions (P4_16 doesn't support them either):
```
log("I'm in action 'a', parameter 'x' is equal to {} and parameter 'y' is equal to {}", x, y);
```

**Comment by endrigoshi** [comment]
@jafingerhut thank you for your reply. that seems a really smart trick! :)

**Comment by antoninbas** [comment]
The solution described in https://github.com/p4lang/behavioral-model/issues/687#issuecomment-440824548 was implemented a while back.
