### ISSUE TITLE
Is StreamStateSaver causing some log output to be not printed?

### ISSUE THREAD

**Issue by jafingerhut** [p4lang/behavioral-model#689]
I had a table in a P4 program with 9 fields in the key, and when running simple_switch with the `--log-console` option, I was fairly consistently seeing only some of the key fields being printed.  I added some debug printf's of my own, and it was not because of the (name != "") condition being false here: https://github.com/p4lang/behavioral-model/blob/master/src/bm_sim/match_units.cpp#L773

I experimented by commenting out the line that creates a StreamStateSaver object: https://github.com/p4lang/behavioral-model/blob/master/src/bm_sim/match_units.cpp#L774

After commenting that out and recompiling, all 9 key fields appeared in the log output as expected.

If I am understanding the purpose of the StreamStateSaver object, it appears like it is intended to cause some number of operations on the stream inside of a curly brace scope to be _undone_ when the scope is exited?

If so, that seems like a bad thing to do here, but I don't really understand the reason for that object's existence in the first place.  It seems like it can cause partial log output in at least some circumstances, though.

**Comment by jafingerhut** [comment]
Addendum: with that change, it also appears that some of the hex key values printed have digits in the wrong order, too.  Very weird.  Debug logging shouldn't need to be complex, should it?

**Comment by jafingerhut** [comment]
I created a new Ubuntu 16.04 Linux VM and installed the latest source code of p4c and behavioral-model on it, and when running with the same BMv2 JSON file it does _not_ have this issue where sometimes, some lines of the table's search key do not appear in the log.  Strange.

I even tried rebuilding simple_switch from scratch on my Ubuntu 16.04 Linux dev machine from the same version of the source code, and it still _does_ have this issue.

I don't understand how the behavior might differ between the two systems in this way, unless the older dev system has some different versions of libraries or something like that.  Very odd.

**Comment by antoninbas** [comment]
Not sure what to suggest here. The `StreamStateSaver` object is a pretty common way of pushing then popping back the state of  C++ stream (which is modified by `std::left` here). It doesn't "undo" anything that was printed to the stream. It may not be strictly needed for this function because the `ostringstream` object being used is local to the function and we the function is the "top-level" user of the object (it is however needed in `dump_hexstring` which is called by this function). However it shouldn't hurt to use it.

I wonder if moving the `std::left` before the `std::setw` would make a difference... It shouldn't based on my understanding of the `std::setw` documentation but most of the examples I see online use `std::left` before `std::setw`, so maybe it is worth a try.

**Comment by antoninbas** [comment]
Also, is it possible that you have a different gcc version on both machines?

**Comment by jafingerhut** [comment]
Both machines (the one exhibiting the problem, and the newer one that doesn't) give this output:
```
% gcc --version
gcc (Ubuntu 5.4.0-6ubuntu1~16.04.10) 5.4.0 20160609
Copyright (C) 2015 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

I will close this issue, as I don't see any actual problems with the code, and can't explain why one of my machines has this weird issue and the other does not.  Perhaps time to abandon the old VM for a new one.
