### ISSUE TITLE
How to run bmv2 in a server to simulate a P4 switch

### ISSUE THREAD

**Issue by ShiJinYu2017** [p4lang/behavioral-model#693]
actually, I want to use a server as a P4 switch，when I run the BMV2，how can I know the <iface*> in the CLI :```./simple_switch -i 0@<iface0> -i 1@<iface1> <path to JSON file>```.

**Comment by jafingerhut** [comment]
If you have physical ethernet interfaces you want to use, you can use a command like 'ip link show' to find out their names and properties / configuration options, on Linux.

If you want to use virtual Ethernet interfaces, you must create them, and then I believe you get to pick their names.  This bash script creates many virtual Ethernet interfaces with names like veth2, veth4, veth6, etc. up to somewhere around veth18: https://github.com/p4lang/behavioral-model/blob/master/tools/veth_setup.sh

**Comment by shijinyu-bjtu** [comment]
@jafingerhut 
Thank you very much for your help.

**Comment by jafingerhut** [comment]
It is physically possible to configure an IP address to such an interface, but I doubt it will achieve whatever effect it normally would.

For example, assigning an IP address to such an interface will _not_ communicate any information about that IP address to BMv2, or to any control software adding table entries to the BMv2 process.  I cannot think of a reason why you would _want_ to configure an IP address to such an interface.  What do you hope to achieve by doing so?

**Comment by shijinyu-bjtu** [comment]
@jafingerhut 
In fact, the function that I want to achive is more like a gateway than a switch，so I think it is nessary to bind the IP to the physical ethernet interfaces.
the topology looks like:
h1、h2<----->s1<----->s3<----->s2<---------->h3、h4
the h1 and h2 are in the net 192.168.1.1/24,but the h3 and h4 are in the net 192.168.2.1/24.
s3 is a traditional router .

**Comment by jafingerhut** [comment]
If s3 is a traditional router, e.g. one configured via certain commands, and its data plane is not P4 programmable, then using whatever commands have been created for it in order to configure IP addresses on _its_ interfaces should work as it normally does.

If a device is P4-programmable, then the only effect to using Linux commands to assign IP addresses to its physical Ethernet ports will be to inform the Linux kernel of those changes -- it will have 0 effect on the P4 program or its table contents, unless you or someone else has written code to cause the Linux kernel to then communicate with the control plane code of your P4 programmable data plane.  If no one has done that, then assigning IP addresses in that way to ports is useless.

**Comment by antoninbas** [comment]
Closing this since no update
