### ISSUE TITLE
Error while building and installing simple_switch_grpc (undefined reference)

### ISSUE THREAD

**Issue by Maedz** [p4lang/behavioral-model#696]
As a backstory i need to build the simple_switch_grpc to try adding ONOS as a control plane to my p4 switch code.

I have followed the instructions located on https://github.com/p4lang/behavioral-model/tree/master/targets/simple_switch_grpc but i get these errors while running make for the simple_switch_grpc:

/usr/local/lib/libpi.so: undefined reference to `_pi_learn_config_set'
/usr/local/lib/libpi.so: undefined reference to `_pi_act_prof_api_support'
/usr/local/lib/libpi.so: undefined reference to `_pi_clone_session_reset'
/usr/local/lib/libpi.so: undefined reference to `_pi_act_prof_grp_set_mbrs'
/usr/local/lib/libpi.so: undefined reference to `_pi_clone_session_set'

Happy for any help with this, thank you in advance!

**Comment by antoninbas** [comment]
You have to use a compatible version of this repo and p4lang/PI. In general, we make sure that the master branches for both repos work together. In this case, it looks like the version of PI you are using is more recent than your bmv2 version.

Since you are using ONOS, I recommend following their guidelines for which repo versions to use. For ONOS 1.14 (recommended version IIRC), see https://github.com/opennetworkinglab/onos/blob/onos-1.14/tools/dev/p4vm/install-p4-tools.sh#L24

**Comment by Maedz** [comment]
super thanks will test this out tomorrow as it is getting late, closing the ticket!

extra cheers for the suuuuper fast answer!
