### ISSUE TITLE
How to set a table entry priority and lifetime using simple_switch_CLI?

### ISSUE THREAD

**Issue by KB00100100** [p4lang/behavioral-model#792]
Hi all,

   I found that we can set a table entry priority and lifetime using the simple_switch_CLI in the previous issues, also get a help information by running `help table_add`:
![image](https://user-images.githubusercontent.com/37429381/59584371-67e3d700-9110-11e9-977a-8669c5e84b5c.png)

But it seems not working for my installed bmv2 whose version is 1.13.0 
![image](https://user-images.githubusercontent.com/37429381/59584489-c446f680-9110-11e9-8ed5-e75146f7b15b.png)

Also the simple_switch log file does not include any priority information when I running `table_dump` cmd:
![image](https://user-images.githubusercontent.com/37429381/59584639-1e47bc00-9111-11e9-9554-24ca351eeac2.png)

How can I set a table entry priority and lifetime? and How to ensure the setting is active?

**Comment by jafingerhut** [comment]
Priority values cannot be set for tables that have only exact match fields.  There is no need to do so, because at most one entry in such a table could match, since duplicates are not allowed.

Similarly, if a table has one field with match_kind lpm, and the rest are exact, you cannot assign a priority to it.  Its matching priority is _determined_ by the length of the prefix.  Longer matching prefixes are always higher priority than shorter matching prefixes.  Thus no priority value may be specified on the simple_switch_CLI command line for such tables.

You must assign a priority for any entry you add to a table that has at least one ternary or range field.  It is an error if you do not specify a priority value when adding entries to such tables.

All of the above should be documented here in the behavioral-model repository: https://github.com/p4lang/behavioral-model/blob/master/docs/simple_switch.md#table-match-kinds-supported

I am less familiar with which kinds of tables can have lifetimes on the entries.  There is an option for tables to have a configurable timeout value when adding entries, such that if an entry is not matched while processing data packets for that time interval T, a notification message is sent to the control plane software about this event.  I do not have any documentation to point you about this, except in the P4Runtime specification, but I suspect that simple_switch supports this even if you use the Thrift API.  I have not used it before, so cannot provide details on it.

**Comment by antoninbas** [comment]
You can use the `table_set_timeout` runtime CLI command to set an entry's TTL if the P4 table supports it. To enable support, I think you need to declare your table with the `support_timeout: True` property.

**Comment by antoninbas** [comment]
Closing this issue, the question was answered.
