### ISSUE TITLE
How to assign a fixed length field to varbit

### ISSUE THREAD

**Issue by ShiJinYu2017** [p4lang/behavioral-model#796]
I have a header struct like 
```
header sinet_dstaddr_t {
    varbit<256> dstAddr; 
}
```
then I tried to assign a fixed length field to it ,but failed.
```
sinet.p4(224): error: AssignmentStatement: Cannot unify bit<64> to varbit<256>
    hdr.sinet_dst.dstAddr = meta.sinetAddr_dst;
```
I don't how to do it ,thanks for you help.

**Comment by jafingerhut** [comment]
The P4_16 language spec defines very very few operations that can be done upon values of type `varbit<W>`, such that their main use case is to carry variable-length packet headers in received packets through to output packets (or remove those headers if you invalidate them).

In particular, they can be assigned to another value with the same `varbit<W>` type, or compared against another with `==` or `!=`.  They can be part of headers upon which you perform an extract, emit, or setInvalid() call.  They can be part of a header upon which you do a setValid() method, but that isn't very useful, because there are no supported mechanisms for initializing such a field, except as mentioned before -- copying it from another field of the same type.  They cannot be cast to or from any other types.

**Comment by jafingerhut** [comment]
Perhaps if you described the overall packet processing effect you are trying to achieve, we may be able to help find a supported way.  The README on this page might help: https://github.com/jafingerhut/p4-guide/tree/master/variable-length-header

**Comment by antoninbas** [comment]
Closing this issue since it is inactive.
