### ISSUE TITLE
Add intrinsic metadata fields like enq/deq_qdepth but in units of bytes?

### ISSUE THREAD

**Issue by jafingerhut** [p4lang/behavioral-model#841]
Most of the applications I am aware of for queue depths require them to be in units of total bytes, or a similar measure that is at least approximately the total size of all packets in the queue (e.g. "cells" for some ASICs), rather than the number of packets, which is what I believe the current v1model fields enq_qdepth and deq_qdepth measure.

Given that there might be some people out there using enq_qdepth and deq_qdepth with their current values, perhaps adding new fields in units of bytes might be better than changing what the existing names measure?  e.g. perhaps enq_qdepth_bytes and deq_qdepth_bytes?

**Comment by hesingh** [comment]
I have also generated json for the code changes and this is the relevant output.

```
"transitions" : [
            {
              "type" : "hexstr",
              "value" : "0x010800",
              "mask" : "0x010806",
              "next_state" : "parse_ipv4"
            },
```

**Comment by antoninbas** [comment]
@jafingerhut Sorry for the delay. I'm fine with that, but is this the right place to discuss adding new fields to v1model.p4? Maybe this should be discussed at the next LDWG. The changes in bmv2 / simple_switch should be quite straightforward, although it will require a bit of work since nothing is keeping track of the number of bytes in the buffer at the moment. The buffer implementation is actually not even aware it is storing "packets", so we would have to change that.

**Comment by jafingerhut** [comment]
One property of this suggested addition is that it is completely backwards compatible, as far as I can tell.  No existing v1model programs access non-existent fields of standard_metadata, because they would get an error when compiling.  Adding new fields with new names is thus safe for all existing programs.

I do not mind bringing up the question in the LDWG.  As far as I can tell, there are a few active users of v1model, but it seems mostly for teaching and testing purposes.

As far as an implementation, if every existing queue in the packet buffer could be enhanced with a "current number of bytes in this queue", that would seem to do it, but I do not know the C++ classes involved.
