### ISSUE TITLE
Implementing match_kind optional in simple_switch?

### ISSUE THREAD

**Issue by jafingerhut** [p4lang/behavioral-model#844]
Related to this PR for p4c: https://github.com/p4lang/p4c/pull/2141

At least couple of possible approaches are possible here:

+ add a match_kind "optional" to the BMv2 JSON file, including defining how such fields should be described in the "entries" section of the BMv2 JSON file when the P4 source code has "const entries" for a table with a match_kind optional field as part of its key

+ turn all match_kind "optional" fields in P4_16 source code into "ternary" in the BMv2 JSON.  Possible down side: The information about the field being "optional" in the source code is then represented nowhere in the BMv2 JSON file, so simple_switch would have no information on which it could know that it should reject table entry insert/modify operations that used a mask that should not be allowed for "optional" fields.

Any preferences for one of those two approaches?  Or some third option I'm not thinking of?

**Comment by jafingerhut** [comment]
Addendum to previous comment: The second option could still have the knowledge of which table search key fields were match_kind "optional" in the P4Info file, so the P4Runtime API should still be able to enforce the mask restrictions on them, even if the BMv2 JSON file called the ternary.  I think it would only be the Thrift API, or others that did not have some other source of information outside of the BMv2 JSON file, that would lose that information and "believe" that those fields were "ternary" in the source code.  Maybe that is an acceptable loss of information for Thrift API clients?

**Comment by antoninbas** [comment]
I think the decision based on the discussion we had in https://github.com/p4lang/behavioral-model/pull/845 is to go with your second option.

**Comment by jafingerhut** [comment]
Antonin, where do you believe code changes would need to be made in order for simple_switch_grpc to support the new OPTIONAL match_kind in a P4Info file?

I am assuming that would require first merging in a change like in this p4lang/p4runtime PR: https://github.com/p4lang/p4runtime/pull/259

but I suspect that more is needed?

**Comment by antoninbas** [comment]
Most of the changes will be in https://github.com/p4lang/PI.

You can look for occurrences of `TERNARY` in https://github.com/p4lang/PI/blob/master/proto/frontend/src/device_mgr.cpp. Unfortunately, all the changes will not be contained in this file. The P4Info message is translated into a C struct when `SetForwadingPipelineConfig` pushes a new config. We then use that in-memory struct when processing P4Runtime Write RPCs (to validate the table entry, etc...). So that struct, which is part of the PI C library will need to store information about which field is an optional match.

(1) One way to do that is to support `OPTIONAL` as a match type (https://github.com/p4lang/PI/blob/master/include/PI/p4info/tables.h#L33). That will have some long ramifications in that PI targets will need to support that new match type. That includes the bmv2 one (https://github.com/p4lang/behavioral-model/blob/master/PI/src/pi_tables_imp.cpp#L68) but probably others as well. That puts a burden on targets, but it is probably the best solution.

(2) An alternative solution is to add a new struct field to [pi_p4info_match_field_info_t](https://github.com/p4lang/PI/blob/master/include/PI/p4info/tables.h#L45) which stores the fact that the match type is optional (but the actual `match_type` field is set to `TERNARY`). That limits the amount of code changes (target code does not need to change), but is still a bit disruptive because it breaks ABI backward compatibility.

Solution (1) is probably the right way to go, given that optional is going to be a first-class citizen in v1model. It's also not as bad as adding optional to the bmv2 JSON IMO. I now wish that we had made this an annotation :), it would have been more straightforward to support.

The changes to the PI library may be a bit tricky, so you may want to punt it to me.

**Comment by jafingerhut** [comment]
I am certainly happy if someone else wants to make the necessary changes to the PI library, which I have not delved into before at all.  I mainly had an itch to scratch wondering how many changes would be required in p4c and behavioral-model code to support this.

**Comment by stefanheule** [comment]
I agree that options (2) from Antonin seems like the right way to go, and I am okay having bmv2 implement optional as just mapping it to ternary (the second bullet in the original message).

One general comment is that there is also another proposal at https://github.com/p4lang/p4-spec/issues/795 which proposes to add yet another match kind.  If there is any work that can be shared between them (or general improvements to make adding match kinds easier in the future), that might be worth thinking about.  But I'm not sure I have a concrete proposal to make that easier.

**Comment by jafingerhut** [comment]
I do not know if there are any ways to make adding match kinds easier in the future.  Or rather, I am sure there are such ways that can be devised, but whenever you are adding one new X, devising ways to make adding new Xs more automated/pluggable in the future seem likely to be significantly more work than adding the one X at hand.

At the moment, I am hacking around seeing how to add `optional`, and what the choices are for doing so in the existing code.

I have a hard time imagining any changes to the open source code base that adding a new match kind doesn't involve modifying code in at least the following, because the implementation of match kind is spread across all of those places:
+ p4c - front end, and back end for writing P4Info file at least, and also bmv2 back end if BMv2 JSON files are affected
+ behavioral-model - we got lucky with `optional` because we can fake it with `ternary`, otherwise there would be many changes there for `optional`, too
+ p4runtime
+ PI

Adding the other `set` match kind, where simply using `ternary` or some other existing match kind is definitely not a solution, it will be strictly more work to do than the current PRs for adding match kind `optional`.  The PRs adding `optional` would be a good place to start looking whenever adding another.

Things that would make implementing `set` more work than `optional`:
+ you would need to create syntax for `const entries` in P4_16 source code for that match kind, and parse it, create IR for it, and back end support for it in P4Info and bmv2 back ends
+ Either you would have no support for the simple_switch_CLI and Thrift APIs for `set` match kind, or you would need to extend them, with code changes I haven't even tried to guesstimate.  The currently proposed changes for `optional` snuck out of this category of changes by reusing `ternary` for now.
+ The parts of behavioral-model that parse the BMv2 JSON file would need extending, for the new match kind, and also to read the updated const entries for `set` from it.  Also for data packet matching behavior, and for control plane updates to tables with those kinds of fields.

**Comment by antoninbas** [comment]
I'm going to close this as p4.org software now supports the `OPTIONAL` match kind.

It is indeed pretty hard to add a new match kind to bmv2 with the current implementation. The code tries to pick the best implementation based on the combination of match types in a table, so there is no "uniform" implementation where we just go through the entries linearly (no matter what the table key is like) and perform a conjunction of all the different matches. For example, a table whose only match field is an LPM will be implemented as a trie, but so will a table with `N` exact matches and one LPM. It's going to take some effort to introduce that linear search mechanism as an alternative implementation that can be used as a convenient fallback for all new match types (for which we cannot or don't want to "refine" the implementation), with very little code required for each new match introduced.

**Comment by antoninbas** [comment]
Opened a separate issue to refactor the implementation: https://github.com/p4lang/behavioral-model/issues/870
