### ISSUE TITLE
Difference between ingress and egress pipeline

### ISSUE THREAD

**Issue by Blandine11** [p4lang/behavioral-model#848]
Hello,
I want to know the difference between ingress and egress pipelines.
I would like to know what we can do in a pipeline (exp: ingress) and we can't do in the other (exp: egress). Or what it is advised to do in each pipeline?

Regards

**Comment by jafingerhut** [comment]
First of all, in P4_16, whether there even is an ingress and egress pipeline, or some other pipelines, depends upon which architecture you are using.  So the answer definitely depends upon the architecture.

For the v1model architecture, I think most or all of the answers can be learned from reading this: https://github.com/p4lang/behavioral-model/blob/master/docs/simple_switch.md  It does not have a single table or section anywhere summarizing what you can do in ingress vs. what you can do in egress -- it is spread over the document.  But the document is not terribly long, and contains many other details that you might be interested to learn.

For the Portable Switch Architecture (PSA), which is similar but not identical, the answers are in the PSA specification, which you can find here: https://p4.org/specs  but I suspect since there is no open source implementation of that available yet, you might want to focus on the v1model architecture first.

There are some proprietary architectures that exist for particular devices, and you would need to consult their documentation.

One difference that is common for all of them that I know of is: you must decide on the packet's output port, or output ports if your P4 program decides to do multicast replication, during ingress.  In egress, you can either drop the packet or let it go to its already-determined output port, but cannot change the output port.

**Comment by Blandine11** [comment]
Hello Andy,

Thank you for your quick response.
I help me to understand.

Regards

Le lun. 20 janv. 2020 à 20:02, Andy Fingerhut <notifications@github.com> a
écrit :

**Comment by Blandine11** [comment]
Thank you ,

It help me to understand.

Regards
