### ISSUE TITLE
bmv2's CLI

### ISSUE THREAD

**Issue by Blandine11** [p4lang/behavioral-model#867]
Hello,

I'm confuse about something and hope someone could help me. 
Q1 : I want to know if the  bmv2's CLI is a CLI that permit us to run instructions directly on the switch or it is a controler interface that  sends  instructions on the switch trought thrift message format?
If it is not a controler interface, that means that both control plan and data plan are embeded in bmv2's switch?

Q2 : When we configure tables entries in the control plan (controler), just the parameters needed are send to data plan during runtime when there is a match or the entire entries are load in the transmission table of each switch?

Q3 : When Parser parses a packet. It extracts exactly the number of bits in header fields or Parser recognizes packets headers? For exemple, Is it correct to do the following ?:

header ethernet_t
{
bit<48> dstAddr;
bit<48> srcAddr;
}
Not : I did not give the ethernet type field (bit<16> ).
header ipv4_t
{
   bit<4>    version;
    bit<4>    ihl;
    bit<8>    diffserv;
    bit<16>   totalLen;
...
}
the total legth of ipv4 version + ihl + diffserv = 16 bits (bit<16>).
What I want to know is, since I did not extract last 16 bits of ethernet header, the values of the three first  fields will be correct or they will be populated with the 16 bits left on the ethernet header?

**Comment by jafingerhut** [comment]
You wrote: Q1 : I want to know if the bmv2's CLI is a CLI that permit us to run instructions directly on the switch or it is a controler interface that sends instructions on the switch trought thrift message format?
If it is not a controler interface, that means that both control plan and data plan are embeded in bmv2's switch?

My response to Q1: The simple_switch_CLI command starts by attempting to make a TCP connection to a simple_switch process, over which it will use the Thrift message format to send messages to the simple_switch process, and receive responses back.  There are command line options to simple_switch_CLI `--thrift-ip` and `--thrift-port` that directs it where to attempt to make this connection, but if you do not specify them, it defaults to connecting to the local host, and a default TCP port number.


You wrote: Q2 : When we configure tables entries in the control plan (controler), just the parameters needed are send to data plan during runtime when there is a match or the entire entries are load in the transmission table of each switch?

My response to Q2: I am not sure I understand the question, but will say some things that might be the answer, and if they are not, ask a separate question.  When the controller wants to add a table entry, it sends the match criteria (e.g. value and mask for ternary fields, value and prefix length for lpm fields, etc.), the action name/identifier, and the action parameters.  The switch then parses this message, does whatever it needs to do to install the table entry into the data plane implementation (into software data structures for bmv2 simple_switch, or hardware tables for a switch ASIC), and acknowledges the request from the controller with success or failure status.  Without any of those parts of the data, the switch does not have enough information to know what to add -- the action parameters are not enough.


Q3 : When Parser parses a packet. It extracts exactly the number of bits in header fields or Parser recognizes packets headers?

My response to Q3: P4 does not have built into it the definitions of any headers that exist in IEEE or IETF standards, not even Ethernet.  If you define a header to have a particular sequence of bits, parser extract statement will copy that many bits starting at the current 'parser cursor position' into the header variable you specify: no more, and no less (unless the end of the packet is reached before the copying is complete, in which case the header will not be made valid and a parser error occurs).

In your example, if the sender sent bits that it interpreted as an ether type after the dest MAC address, the receiving parser you wrote will interpret those 16 bits as the first 16 bits of the IPv4 header.  On the links between switches, bits are bits.  They do not come labeled with 'names' on them anywhere.  The whole job of the parser is to give some of those bits names, and P4, like most other programming languages, does what you tell it, which isn't always what you were thinking. :-)

**Comment by jafingerhut** [comment]
Additional note about your question Q1: The simple_switch process does not include the controller software, as hopefully my answer above made clear.  However, the simple_switch process _does_ include some more software than only the data plane.  It also includes the "server" or "switch" side of the control plane software, that knows how to parse Thrift API messages, and send Thrift API responses back in responses to them.  That isn't the controller, but it is code I would consider _not_ in the data plane, because that Thrift-related code in simple_switch is not executed when packets are received on a switch port, only when Thrift messages are received from the controller.

**Comment by Blandine11** [comment]
Ok, thanks.
About my question Q1, we can say that simple_switch_CLI is a software used the establish TCP connexion to switch process in order to send tables entries.
About my question Q2, I just wanted to know if the tables entries are installed in switchs statically  or dynamically when there is a packet that match. But about what you said ,I think that controller installs or sends all matching information to switch. Switchs install them statically and read them to process packets. If we define news matching informations, the controller will send them again to switch.
I don't know if I'm right.

**Comment by jafingerhut** [comment]
You can create a P4-programmable switch that, when it experiences a miss in some table, sends a message to the controller that means "I got a miss when looking up key X in table Y", and the controller software could be written to process those messages by deciding whether it "thinks" there ought to be additional entries in table Y (and perhaps other tables, too), and sends control plane messages to the switch adding new table entries.  Such things will typically happen many milliseconds after the packet that got the miss, depending upon latency between switch and controller, and how long the controller software takes deciding what it wants to do.

With a P4 programmable device, all of that is implemented in a combination of P4 code, and controller code.  You have the option to do that, but you do not have to do that when a table misses, only if you want it to work that way.

**Comment by jafingerhut** [comment]
Also, one perspective is that the simple_switch_CLI program _is_ controller software.  But, it only adds table entries when you type a command, and not under any other conditions.  So it is good for debug and learning purposes, but not good for adding thousands of entries into a table, directed by a program you write.

**Comment by Blandine11** [comment]
Ok. I see.
Thank you a lot.
The other things I want to know are:
Q1 : Why P4Runtime need for ''.p4info'' to configure control plan API but simple_switch_CLI does not need this? Is it because the API used by simple_switch_CLI is fixed ?
Q2 :Since the functions are executed in the dataplane, I don't understand the RPC (Remote Procedure Call) communication between control plan (Thrift/gRPC client) and data plan (Thrift/gRPC server).

**Comment by jafingerhut** [comment]
Q1: Why P4Runtime need for ''.p4info'' to configure control plan API but simple_switch_CLI does not need this? Is it because the API used by simple_switch_CLI is fixed ?

My answer to Q1:

@antoninbas can tell me if I am wrong in any details here, but I believe the reason that simple_switch_CLI does not have anything like a ".p4info" file is _not_ because it is fixed to one particular P4 program.  It is because the Thrift API uses table names, i.e. strings of characters like "ingress.my_favorite_table", in every message that refers to that table.  That takes more space in the messages, and requires the receiver of the message to read the entire variable length thing, then use something like a hash table to look it up to see if it is a legal name for the currently loaded program.

The P4Runtime API uses fixed-length numeric ids for all 'objects', including tables, counters, meters, etc.  The space and run time improvements are not huge, but there are some.  These numeric ids are not required to be part of your P4 source code -- typically the compiler generates them.  So, the controller and switch need to agree on what these numeric IDs are, and the P4Info file is a way to get that information to both.


Q2 :Since the functions are executed in the dataplane, I don't understand the RPC (Remote Procedure Call) communication between control plan (Thrift/gRPC client) and data plan (Thrift/gRPC server).

My answer to Q2: What functions are you referring to here that are executed in the data plane?

If it is hurting your understanding, do not think of P4 Thrift / P4Runtime messages as RPC calls.  They are just messages.  Some of the messages defined in the P4Runtime API from switch/server to controller/client are definitely _not_ RPC calls, but notification messages, e.g. if the data plane generates a digest message, these are sent as asynchronous notification messages.  Similarly for PacketIn / PacketOut messages.  I suppose if one stretched their imagination you could try to think of those as RPC messages, but I can't think of any benefit, only possible confusion, to trying to understand them as RPC.

There are messages from the controller/client to the switch/server that request operations to be performed by the switch, such as "add this table entry to table foo", but how the server does that might be executing one function, or 38 functions in a deep call stack.  The client doesn't care, as long as the job gets done.

**Comment by antoninbas** [comment]
`simple_switch_CLI` consumes the bmv2 JSON (it is retrieved over the Thrift API when you start `simple_switch_CLI`). It then uses the information included in the bmv2 JSON (which in this regard is *almost* a superset of P4Info) to validate & format user-provided inputs before generating the Thrift RPCs. If you start `simple_switch` with `--no-p4`, you will not be able to do anything useful with `simple_switch_CLI` until you load a JSON.

P4Runtime takes a different approach. While with the "legacy" approach, `simple_switch` requires the JSON to be provided when starting the bmv2 process, when using P4Runtime with `simple_switch_grpc`, you usually do not provide the JSON when starting the bmv2 process. Instead, the JSON & P4Info are provided to bmv2 by P4Runtime (by the P4Runtime client). In theory, because *almost* all the information included in P4Info is also included in the bmv2 JSON (this is not really true any more, e.g. with OPTIONAL support), it may be enough for a client to simply provide the bmv2 JSON (and it used to work this way). However, the P4Runtime server implementation is target-independent, and therefore cannot work this way.

**Comment by antoninbas** [comment]
Closing this since no update. Feel free to re-open if you have further questions.
