### ISSUE TITLE
What does that mean about first phase of device update

### ISSUE THREAD

**Issue by apathy72115** [p4lang/behavioral-model#869]
Hello,
I would like to use a p4runtime controller send SetforwardingPipelineConfig message to bmv2(simple_switch_grpc),when I connect it for the fisrt time with SetforwardingPipelineConfig message is fine, but second time when I use p4runtime controller try to connect it,the bmv2 will occur an error message down below.

![0303](https://user-images.githubusercontent.com/22795379/75737970-fac6af00-5d3b-11ea-9045-a5f81ca78e22.png)

I want to know what does that mean about first phase of device update,Is any solution can solve it?

**Comment by antoninbas** [comment]
Could you share the P4Runtime messages you are sending? Or maybe the code you are using to build these messages? There is no reason for the second `SetforwardingPipelineConfig` to fail if the first one succeeded, unless for example you did a `VERIFY_AND_SAVE` without a corresponding `COMMIT` (bmv2 does not like that). But most people use `VERIFY_AND_COMMIT`.

**Comment by antoninbas** [comment]
By the way, 2 observations:
 * you do not need to provide the JSON file when starting `simple_switch_grpc`. The JSON is provided through P4Runtime by `SetforwardingPipelineConfig`. You can replace `s3_05.json` with `--no-p4`.
 * you are using the old message format in `SetforwardingPipelineConfig`, which is why you are getting a warning. `p4::tmp::P4DeviceConfig` is no longer required (the bmv2 JSON is used directly as the `p4_device_config` field - https://github.com/p4lang/p4runtime/blob/v1.1.0/proto/p4/v1/p4runtime.proto#L680). Things should still work but support for the legacy `p4::tmp::P4DeviceConfig` message will be removed in the future.

**Comment by apathy72115** [comment]
Thanks for your reply!
It work with the `SetforwardingPipelineConfig` action `VERIFY_AND_COMMIT`, I used `VERIFY_AND_SAVE` in this message before.
