### ISSUE TITLE
Compiler for PSA

### ISSUE THREAD

**Issue by Blandine11** [p4lang/behavioral-model#873]
Hello Guys,
Can you help me, please?
I want to know if the implémentation of PSA architecture is finish now.
If yes, what is the compiler for P4 code based on PSA architecture.
Can we use p4c or p4c-bm2-ss to compile code based on PSA architecture?

I will appreciate your help

**Comment by jafingerhut** [comment]
The implementation of PSA has been worked on, but is still incomplete.  It is in a state where a few very simple programs compile and work, but most programs either do not compile, or compile to incorrect results that do not behave as they should.  It seems likely that someone will be working towards finishing it by the second half of 2020.

**Comment by Blandine11** [comment]
Ok Guy,

Thank you so much.

Regards

**Comment by Blandine11** [comment]
Excuse me,
So the compiler used to (or try to) compile PSA code today is p4c compiler?

Regards

**Comment by jafingerhut** [comment]
If you set up an Ubuntu Linux machine (or virtual machine) version 16.04 or 18.04 and install behavioral-model, p4c, etc. for example using a shell script like the one described here: https://github.com/jafingerhut/p4-guide/blob/master/bin/README-install-troubleshooting.md

then you can use these commands to compile a few working PSA architecture programs that are included as test programs with the p4c compiler:
```
cd p4c/testdata/p4_16_samples
p4c-bm2-psa psa-counter1.p4
```
Then run the command `psa_switch` instead of `simple_switch` with the compiled BMv2 JSON file that `p4c-bm2-psa` produces.

There are relatively simple programs that fail to produce working code, or do not compile, a few of which are attached to these issues:

https://github.com/p4lang/p4c/issues/1918
https://github.com/p4lang/p4c/issues/1919
https://github.com/p4lang/p4c/issues/1827
https://github.com/p4lang/p4c/issues/1329

**Comment by Blandine11** [comment]
Ok Guy,

Thank you ;)

Regards
