### ISSUE TITLE
BMv2 several questions | interfaces | frame check sequence

### ISSUE THREAD

**Issue by MichaelHoeflmaier** [p4lang/behavioral-model#882]
Dear P4-Community,
I am new to P4 and have still some conceptional question. I already have some experience with some of the official tutorial examples.

My questions:

- Is Bmv2 only supporting Ethernet-interfaces or can I use any interface which is supported within the linux-kernel? I am asking this because I want to use P4 in conjunction with several hosts in a mininet-enviroment with all bus interfaces.
- If this is not possible, is there any way to emulate such a system on a ethernet-basis without using multicast?
- Tutorial environment: There in the code does the tutorial environment set the interface-type as Ethernet for the switches and hosts? I already did an extenise search, but didn't manage to find anything.
- I am also not quiet sure about checksum-computation in P4. I am able to compute the checksum of a custom header, but I can't manage to compute it over the entire custom packet like the FCS at the end of an ethernet frame. Is computing a custom "FCS" even possible in P4?

- Additionally in my parser I want to make a transition decision on a field of the next, not yet extracted header. Normally I would use lookup, but the header-field I want to read is not the first but second and current() is not available anymore. What should I use here? 
Example of my problem.: 
```
header myHeader_t {
    bit<1>    firstBit;
    bit<1>    secondBit;
}

state parse_two_type{
        transition select("lookahead" on secondBit) {
            1: parse_a;
            0: parse_b;
        }
    }
```
My ugly solution up to now:
```
header myHeaderOne_t {
    bit<1>    firstBit;
}

header myHeaderTwo_t {
    bit<1>    secondBit;
}

state parse_two_type{
        packet.extract(hdrmyHeaderOne);
        transition select(packet.lookahead<bit<1>>()) {
            1: parse_a;
            0: parse_b;
        }
    }
```

Already thank you for your time reading in advance.

**Comment by jafingerhut** [comment]
I have never tried using non-Ethernet interfaces with BMv2, personally, so not sure whether there are any limitations there.  As far as the header formats, one must explicitly define and parse an Ethernet header in one's P4 programs in order to access the fields of an Ethernet header, so that is not "baked in".  There may be other places in BMv2's implementation that might assume Ethernet, though.

There are very few features in the open source P4 development tools that deal with entire payloads.  The only two that spring to mind are for doing IP checksums over the entire payload of a packet in the v1model architecture using verify_checksum_with_payload or update_checksum_with_payload.

Most high speed implementations support very flexible access to the first N bytes of the packet, where N is implementation-specific (e.g. 128 bytes, 256 bytes, or somewhere in that neighborhood).  The parts of such a high-speed implementation that handle Ethernet FCS are not P4-programmable, but hard-wired.

**Comment by MichaelHoe** [comment]
Okay I will have a futher look at the interface-topic and if I find anything usefull I will post it below.

Thank you for this tipp: verify_checksum_with_payload
I will try it out.
