### ISSUE TITLE
Is there a way to call the xxhash64 calcuation via p4 v1model?

### ISSUE THREAD

**Issue by csqjxiao** [p4lang/behavioral-model#884]
For P4 developers, the following list of hash functions are readily available to use, according to the "p4c/p4include/v1model.p4" file. 

```
enum HashAlgorithm {
    crc32,
    crc32_custom,
    crc16,
    crc16_custom,
    random,
    identity,
    csum16,
    xor16
}
```

But most of these hash functions, such as crc32 and crc32_custom, have linear dependencies between input key and hash value. They are primarily used for generating checksums for arrival packets. My P4 application needs to call some good-quality hash functions like xxhash or mumurhash. I found in the file "behavioral-model/src/bm_sim/calculations.cpp", bmv2 switch has already implemented the very fast xxHash function under the name "xxh64". I wonder if there is a way to access this hash function from my P4 code. 

I saw the previous post about modifying the P4 v1model.  https://github.com/p4lang/behavioral-model/issues/570 . It put a recommendation to change the v1model.

```
#include <v1model.p4>
enum HashAlgorithm {
    crc32,
    ...
    xor16
    hash_ex
}
```

How can I let bmv2 implement the enum HashAlgorithm.hashex (or HashAlgorithm.random)  by xxh64? Thanks for shedding some light on this issue.

**Comment by antoninbas** [comment]
You can either follow the instructions in https://github.com/p4lang/behavioral-model/issues/570 or you can always manually edit the JSON file generated by the p4c compiler to use the desired hash function instead of "random" or whatever you use in the P4 program.

There isn't really any other alternative, unless you can convince the P4 Language Design Working Group which owns v1model to include new hash algorithms in the architecture.

**Comment by csqjxiao** [comment]
Thanks. It seems that we have to deviate from the v1model and use the additional hash function hash_ex.
