### ISSUE TITLE
Add new Runtime_CLi to simple_switch

### ISSUE THREAD

**Issue by qzCoder** [p4lang/behavioral-model#886]
I want add some new CLI to simple_switch, eg pause a queue, how can I do it. or what files should I modify in simple_switch folder?

**Comment by qzCoder** [comment]
anybody here

**Comment by jafingerhut** [comment]
There are people who notice new issues here, yes.  I think most of them have day jobs, and have life responsibilities other than answering issues here.

I am going to recommend here not a cookbook approach of specific commands for you to run that will be the full answer, more some recommendations of how I would approach such a task, and have used this method successfully on many software projects in general.

Have you already run simple_switch_CLI and/or runtime_CLI and executed commands successfully in it?  If not, I would recommend first doing that.

Now pick one of the commands that you have run successfully, and search for all files whose names contain runtime_CLI and/or simple_switch_CLI in this repository, e.g. in your cloned copy on Linux, run a command like `find . | grep -i runtime_cli'.  At least one should be a Python program.  Search within that file for the name of the command, e.g. table_dump or whatever command you want to learn from.  Add a new print statement to Python methods you find that appear to implement that command, reinstall simple_switch using the appropriate commands you find in the readme, or here: https://github.com/jafingerhut/p4-guide/blob/master/bin/build-behavioral-model.sh#L68-L82

Run simple_switch_CLI or runtime_CLI command after that reinstallation step, and execute the command that you added a print statement to.  Did you observe your print statement executing, because you saw its output appear?  If so, great.  Now you know part of the code that is executed when that command is run.  If not, try adding more print statements in other likely looking places until you do find the code that is executing.

Once you find it, now look at the implementation of that command, and copy, paste, and edit the copy to replace occurrences of the original command name with the new command you want to create.  If you get stuck, try asking _with specific changes that you have made, preferably published in your own public Github repository where others can see exactly what they are_, and say what you tried, and what it did, and how it is different than what you expected.

**Comment by qzCoder** [comment]
> There are people who notice new issues here, yes. I think most of them have day jobs, and have life responsibilities other than answering issues here.
> 
> I am going to recommend here not a cookbook approach of specific commands for you to run that will be the full answer, more some recommendations of how I would approach such a task, and have used this method successfully on many software projects in general.
> 
> Have you already run simple_switch_CLI and/or runtime_CLI and executed commands successfully in it? If not, I would recommend first doing that.
> 
> Now pick one of the commands that you have run successfully, and search for all files whose names contain runtime_CLI and/or simple_switch_CLI in this repository, e.g. in your cloned copy on Linux, run a command like `find . | grep -i runtime_cli'. At least one should be a Python program. Search within that file for the name of the command, e.g. table_dump or whatever command you want to learn from. Add a new print statement to Python methods you find that appear to implement that command, reinstall simple_switch using the appropriate commands you find in the readme, or here: https://github.com/jafingerhut/p4-guide/blob/master/bin/build-behavioral-model.sh#L68-L82
> 
> Run simple_switch_CLI or runtime_CLI command after that reinstallation step, and execute the command that you added a print statement to. Did you observe your print statement executing, because you saw its output appear? If so, great. Now you know part of the code that is executed when that command is run. If not, try adding more print statements in other likely looking places until you do find the code that is executing.
> 
> Once you find it, now look at the implementation of that command, and copy, paste, and edit the copy to replace occurrences of the original command name with the new command you want to create. If you get stuck, try asking _with specific changes that you have made, preferably published in your own public Github repository where others can see exactly what they are_, and say what you tried, and what it did, and how it is different than what you expected.

Thanks for your reply, I will try it

**Comment by qzCoder** [comment]
> There are people who notice new issues here, yes. I think most of them have day jobs, and have life responsibilities other than answering issues here.
> 
> I am going to recommend here not a cookbook approach of specific commands for you to run that will be the full answer, more some recommendations of how I would approach such a task, and have used this method successfully on many software projects in general.
> 
> Have you already run simple_switch_CLI and/or runtime_CLI and executed commands successfully in it? If not, I would recommend first doing that.
> 
> Now pick one of the commands that you have run successfully, and search for all files whose names contain runtime_CLI and/or simple_switch_CLI in this repository, e.g. in your cloned copy on Linux, run a command like `find . | grep -i runtime_cli'. At least one should be a Python program. Search within that file for the name of the command, e.g. table_dump or whatever command you want to learn from. Add a new print statement to Python methods you find that appear to implement that command, reinstall simple_switch using the appropriate commands you find in the readme, or here: https://github.com/jafingerhut/p4-guide/blob/master/bin/build-behavioral-model.sh#L68-L82
> 
> Run simple_switch_CLI or runtime_CLI command after that reinstallation step, and execute the command that you added a print statement to. Did you observe your print statement executing, because you saw its output appear? If so, great. Now you know part of the code that is executed when that command is run. If not, try adding more print statements in other likely looking places until you do find the code that is executing.
> 
> Once you find it, now look at the implementation of that command, and copy, paste, and edit the copy to replace occurrences of the original command name with the new command you want to create. If you get stuck, try asking _with specific changes that you have made, preferably published in your own public Github repository where others can see exactly what they are_, and say what you tried, and what it did, and how it is different than what you expected.

Thanks for your reply, I will try it
