### ISSUE TITLE
New question concerning priority queueing

### ISSUE THREAD

**Issue by MichaelHoe** [p4lang/behavioral-model#896]
I have some question concerning priority queueing in conjunction with https://github.com/p4lang/behavioral-model/issues/562

There the guide to enabling priority queueing is:
> 
> 
> Only the first 2 steps are required:
> 
>     * Uncomment `#define SSWITCH_PRIORITY_QUEUEING_ON`
> 
>     * Recompile

Is this also necassary when running simple_switch_grpc?
I am not sure of this, because I got priority queuing to "work" on the official tutorial-vm and there `#define SSWITCH_PRIORITY_QUEUEING_ON` is **commented** by default. I guess, therefore it shouldn't work.
To check all of this I tested some things...

My test case:

- I only modified the basic.p4-solution from the offical basic-tutorial (https://github.com/p4lang/tutorials/tree/master/exercises/basic)

- There after Line 113 I added `standard_metadata.priority = (bit<3>)7;`  https://github.com/p4lang/tutorials/blob/d964079ef8381316d32a19307509dd4a97edd070/exercises/basic/solution/basic.p4#L113

- After running this example in the log-file the assignment `standard_metadata.priority = (bit<3>)7` is visible. Therefore I think its working... Am I wrong and it is not? How can I check this any further?

I also made another test case:

- Running another p4-file with `standard_metadata.priority = (bit<3>)7` in it the log file only shows  `standard_metadata.priority =`. Since I use debugging-tables I have verified that `standard_metadata.priority` holds the value `7`.  Is priority queueing working if `standard_metadata.priority` holds an value? Is this just an bug within the log-file?

Concerning recompilation:

- Which command is used for this and do I have to recompile for `simple_switch` too or just for bmv2, when using simple_switch_grpc?

**Comment by antoninbas** [comment]
You can set this field to any value you want since it is defined in v1model.p4, and it will indeed show in the logs (just like if you set any other field), but it will only have an impact on scheduling if you rebuild simple_switch / simple_switch_grpc with `SSWITCH_PRIORITY_QUEUEING_ON` defined.

After you uncomment the line in simple_switch.h, you should just need to run `make` in `targets/simple_switch` and `targets/simple_switch_grpc`. You can also start from a fresh clone and follow the instructions in https://github.com/p4lang/behavioral-model/tree/master/targets/simple_switch_grpc#dependencies-and-build-steps if you prefer.

Unfortunately, I don't think there will be any confirmation in the logs that your changes were actually taken into account correctly when you run your new `simple_switch_grpc` binary. It may be a good idea to add the following at the beginning of the [start_and_return_](https://github.com/p4lang/behavioral-model/blob/master/targets/simple_switch/simple_switch.cpp#L281) implementation, before you rebuild:
```
#ifdef SSWITCH_PRIORITY_QUEUEING_ON
bm::Logger::get()->info("Using priority queueing between ingress and egress");
#endif
```
Don't hesitate to submit this change as a PR too, I think it would be useful to other people as well.
