### ISSUE TITLE
Packet generation 

### ISSUE THREAD

**Issue by sanaa50** [p4lang/behavioral-model#912]
Is it possible for a P4 switch to generate a packet?
If so, how to do that?

**Comment by jafingerhut** [comment]
Neither the v1model nor the PSA architecture provide ways to send out a packet, except in response to receiving a packet.  If you are willing to have some device send your P4-programmable device a packet on the events or times of interest, then you can change those received packets into what you want to send.  The control plane software can also send packets to the P4-programmable device, and it can transform and send them.

There are other P4_16 architectures besides v1model and PSA, typically proprietary ones that do not yet have public specs, that do implement ways to cause packets to be generated, either with a configurable time period, or from certain event triggers designed into the device.

**Comment by jafingerhut** [comment]
Since the v1model architecture has an open source implementation, a person with the proper skills, interest, and/or time could implement ways to send out a packet, without first receiving one. 
 Even for someone who already has the knowledge of the current implementation in some detail, both in p4lang/behavioral-model and p4lang/p4c code, I would guesstimate that would easily take a couple of weeks of effort.  If you do not already have that knowledge, you would have to add some number of additional weeks to come up to speed on the relevant parts of those implementations.

**Comment by sanaa50** [comment]
> Since the v1model architecture has an open source implementation, a person with the proper skills, interest, and/or time could implement ways to send out a packet, without first receiving one.
> Even for someone who already has the knowledge of the current implementation in some detail, both in p4lang/behavioral-model and p4lang/p4c code, I would guesstimate that would easily take a couple of weeks of effort. If you do not already have that knowledge, you would have to add some number of additional weeks to come up to speed on the relevant parts of those implementations.

Very interesting. May be I'll give it a try in my spare time.

Thanks.
