### ISSUE TITLE
About number of tables used in simple_switch on bmv2 simulator

### ISSUE THREAD

**Issue by drobinkent** [p4lang/behavioral-model#921]
I have a P4 program which uses 4 tables. but when I connect to the thrift server using simple_switch_CLI and use the command line interface to dump tables, I have found that there are some  extra tables listed there. Are they from various conditional statements in the program? In real hardware switches does same thing happens? Or it just how the things are implemented in bmv2. 

I am trying to get idea about how many physical stages a data plane program will consume on real hardware switches.

**Comment by jafingerhut** [comment]
The p4c compiler creates additional tables whenever there are things in a P4_16 control that were not in P4_14 controls, because the BMv2 JSON format only explicitly represents conditionals and table invocations within a pipeline.  So assignment statements or action calls directly within a P4_16 control, for example, become new tables that have a single default action that do those things.

If you want to get a very precise idea of how many physical stages an RMT architecture device requires for a P4 program, I would highly recommend using the P4 compiler for such a device and look at the results it produces.

If that is not an option for you, the next best thing is to learn lots of details about what kinds of things can go into the same stage of an RMT hardware device, and which cannot.  Unless your idea of constraints is accurate for a particular device, your estimate will be off, though.

**Comment by drobinkent** [comment]
@jafingerhut thanks a lot for the reply. 

Earlier, I have asked a question in the P4 mailing list, where you gave an excellent reply regarding memory ports. I have 2 more   queries which I think is relevant to both that thread (in P4 mailing list) and  this question also. I am asking them here. I am trying to understand these issues correctly to estimate about real hardware consumption of a P4 program. 

1) Assume we need "n"  read write access to a stateful memory (register, counter ot may be some exotic stateful memory in future), and the hardware have "m" memory ports. Now if, n>m how the compiler maps logical instructions to actual hardware stages? 

2) Let's assume we have a hardware where the stateful memory I/O speed is lower than the pipeline speed. For example, in a 1 Ghz speed pipeline we are using some DRAM based memory which have much lower speed, on such cases we need some kind of CPU like pipeline stall (I assume that sounds much more like an wild use case!! ).  Then how compiler is going to handle that. As far as my understandings, this issue will also arise if we use an extern which also have much lower speed than the pipeline.

**Comment by jafingerhut** [comment]
1. I think the most common response to "P4 program needs more resources than the hardware target provides" is "P4 compiler informs the P4 developer that their program needs more resources than the hardware target provides" and you cannot run that program on that device.  The P4 developer should then try to understand the hardware capabilities better, think more about other ways to achieve their goals, and if they find another way, modify their P4 program to fit within target's capabilities.

2. There are P4-programmable devices with no DRAM, and deterministic 1-packet-per-clock-cycle throughput, because their hardware designs are such that they have made that performance goal a requirement in their design.  P4 the programming language does not mandate such a hardware design -- it is one of many that are possible.  Different hardware designs will lead to different achievable performance, and different sets of P4 programs that can be supported by their hardware-target-specific compilers.

**Comment by drobinkent** [comment]
thanks a lot.
