### ISSUE TITLE
How to read user-defined metadata?

### ISSUE THREAD

**Issue by KuiWei004** [p4lang/behavioral-model#942]
Hello, everyone!

My p4 program is based on PSA arch, in which I defined  user_metadata.
Now , I want to read the user_metadata when psa_switch is running, but I checked the command that runtime_cli provides, and did not find the way to achieve that.

**Comment by antoninbas** [comment]
Metadata fields are only available in the data path and are not exposed through the runtime APIs. The state stored by these fields is also tied to a single packet (more precisely their scope is the execution of a control block for a given packet). So it's unclear to me what you expect such a command to look like.

There is a "gdb-like" debugger available to step through packet execution and inspect field values (https://github.com/p4lang/behavioral-model/blob/master/docs/p4dbg_user_guide.md). However, usually the most convenient way is to log the field value and inspect log messages:
 * if it's used as a match field in a table it will be logged at the time the table is applied
 * otherwise, the `log_msg` extern can be used

"Stateful" registers let you persist some packet data and read it from the control plane. At the moment they are not implemented by psa_switch.

**Comment by jafingerhut** [comment]
Minor correction -- psa_switch _does_ implement P4 register arrays now.  There are a few working test programs checked into the p4lang/p4c repository, like the ones in the files listed below in the testdata/p4_16_samples directory, and they use packets sent in, and output packets checked by, STF tests, and those tests are written such that the tests will not pass unless the register read/write operations are working correctly from the data plane:

psa-register-read-write-bmv2.p4
psa-register-read-write-2-bmv2.p4

I am pretty sure the Thrift APIs work for performing control plane read and write operations to them, too, but have not tried it myself yet.

**Comment by antoninbas** [comment]
Thanks Andy, you're correct. I was going by the observation that there is no extern implementation for registers under https://github.com/p4lang/behavioral-model/tree/master/targets/psa_switch/externs. But I recall now that the p4c backend implements support (temporarily?) by leveraging bmv2 core support for registers (so the generated JSON is the same as for simple_switch).
