### ISSUE TITLE
What is the queue size of the ingress port?

### ISSUE THREAD

**Issue by sanaa50** [p4lang/behavioral-model#943]
Hi.
I want to know the size of BMv2 ingress port queue. How much packet it can hold at a time?
If the size is X,then how much time it is required for the `simple_switch` to fetch the last packet in the queue, that is, the Xth packet?

**Comment by jafingerhut** [comment]
If you care about the performance of BMv2, I would ask you: "Why do you care about its performance?  It was not designed for production packet processing, but for testing P4 programs."   https://github.com/p4lang/behavioral-model/blob/master/docs/performance.md

I do not know how many packets the ingress queue can hold at a time.  I do know that the time required for simple_switch to fetch the last packet in the queue depends on many factors, many of which are described at the article linked above.  There is no straightforward answer like "simple_switch is guaranteed to pull packets from the ingress queue at a rate of 1000 packets per second", because the rate depends upon so many factors.
