### ISSUE TITLE
How to measure processing time

### ISSUE THREAD

**Issue by guimvmatos** [p4lang/behavioral-model#946]
Hi, 

I want to know how is the easier way to measure packets processing time of BMv2 with a specific P4 code. 

Can I do this with cli, debugger or event loggin with nanolog?  Or do I need to do this via P4 code?

If someone have some sample code, it will be good.

**Comment by jafingerhut** [comment]
First, I would recommend reading this article, and realizing that bmv2 is not intended to be the highest-performance software switch out there.  It is intended to be for developing and debugging P4 programs, not for achieving the highest performance one can on a general purpose CPU: https://github.com/p4lang/behavioral-model/blob/master/docs/performance.md

If you realize this about bmv2, and you still want to do your measurements, read on.

There are ingress_timestamp and egress_timestamp metadata fields in the v1model architecture, but as implemented today they are in units of microseconds, which is a fairly coarse measurement for the processing time of an individual packet.  Modifying bmv2 so those are in units of nanoseconds, or processor clock cycles, would give more precise measurements of those.

I suspect one would want measurements of the time to do parsing on its own, and ingress processing, and egress processing.  One way to do that would be to modify this file in bmv2: https://github.com/p4lang/behavioral-model/blob/master/targets/simple_switch/simple_switch.cpp#L502

so that the current time in nanoseconds or processor clock cycles is taken just before and after this line, when packet parsing occurs:
parser->parse(packet.get());

and take the difference and print that out to a log somewhere (perhaps only the total time after every N packets or so, if you do not want the logging time to change the performance very much), and also before and after this line, where ingress processing is done:

https://github.com/p4lang/behavioral-model/blob/master/targets/simple_switch/simple_switch.cpp#L514
    ingress_mau->apply(packet.get());

Here is the corresponding line for where egress processing is done:
https://github.com/p4lang/behavioral-model/blob/master/targets/simple_switch/simple_switch.cpp#L675
    egress_mau->apply(packet.get());
