### ISSUE TITLE
Field psa_egress_deparser_input_metadata.egress_port is not defined..

### ISSUE THREAD

**Issue by castilhorosa** [p4lang/behavioral-model#950]
Hello guys!

I compiled my P4 program into a PSA architecture by using the command below and it seems to me that's ok. I got the json file.

`sudo p4c-bm2-psa --toJSON myProgram.json myProgram.p4`

However, when I try to execute the psa_switch to consume such json file I get the following message:

`$ sudo ./psa_switch -i 0@veth0 -i 1@veth1 ~/Documents/p4_tests/myProgram.json
`
`Calling target program-options parser
Field psa_egress_deparser_input_metadata.egress_port is required by switch target but is not defined`

I thought this may be occurring because in my PC neither p4c and bmv2 was updated to reflect the latest changes, specially this one #939.

However, even updating both p4c and bmv2, I still get the same message telling me that there's something wrong with the field `psa_egress_deparser_input_metadata.egress_port.`

I know psa_switch is not yet complete, but maybe there is something I did wrong. How could I fix this?

Thanks in advance.

**Comment by jfingerh** [comment]
Try this command to compile your program instead of the one you show above with the `--toJSON` option:
```
p4c-bm2-psa -o myProgram.json myProgram.p4
```
There shouldn't be any need to use `sudo`, but I doubt that is the issue.  `--toJSON` does cause a JSON file to be written, that is true, but JSON is a data format that can be used to convey many different kinds of data.  The `--toJSON` option writes an p4c compiler intermediate representation data file that is only intended for p4c developers who want to debug p4c itself.
