### ISSUE TITLE
Is bmv2 support clone? 

### ISSUE THREAD

**Issue by kphf1995cm** [p4lang/behavioral-model#955]
When using bmv2 as target to comple P4-16 program with clone operation (p4c --target bmv2 --arch v1model --std p4-16 copy_to_cpu.p4), some error arised as follow:

error: 1: Unsupported on target 1: must be a constant on this target. Are you using an up-to-date v1mode.p4?

           clone(CloneType.E2E,100);

**Comment by jfingerh** [comment]
I have written a test program for p4c that has been working fine for a couple of years or so.

If you can attach a complete program to a comment (if it is publicly sharable), and the output of the following commands, that might help narrow down the problem:
```
p4c --version
simple_switch --version
```

**Comment by kphf1995cm** [comment]
Is there a requirement for p4c or bmv2 version?

**Comment by kphf1995cm** [comment]
Here is my P4 program
https://github.com/kphf1995cm/P4DAD/blob/master/src/P4DAD_1.p4

**Comment by jafingerhut** [comment]
When I clone that repository and run this command to compile that file:
```
p4c --target bmv2 --arch v1model P4DAD_1.p4
```
it compiles with no errors when I use this version of p4c:
```
$ p4c --version
p4c 1.2.0 (SHA: 1b27cb77c BUILD: DEBUG)
```
That is _NOT_ the minimum version required, though.  This test program uses the clone3 operation, and has compiled successfully since some time in 2018, and probably even back to 2017 before that test program was added.  I doubt you are using a version of p4c older than that (although you do not choose to share what version you are using, so I cannot tell), so perhaps you are using a different command for trying to compile your program than the one I show above?  What command are you trying to run when you compile?

**Comment by jafingerhut** [comment]
Here is a link to the 2-year-old test program that uses the v1model architecture and invokes a clone3 operation, that has been working fine in automated tests since it was added: https://github.com/p4lang/p4c/blob/master/testdata/p4_16_samples/v1model-special-ops-bmv2.p4#L247

**Comment by jafingerhut** [comment]
No follow-up questions for a year on this issue, so closing it.
