### ISSUE TITLE
Digest not recognized 

### ISSUE THREAD

**Issue by mohammedelazzab** [p4lang/behavioral-model#956]
Hello, I added a simple simple digest to a P4 program that compiles and works fine, the tables can be populated properly using P4runtime via GRPC. I use the following structure for the digest : 
```
struct portrate_digest_t {
    @id(1)
    port_t egress_port;
    bit<32> port_rate;
}

portrate_digest_t port_digest_msg;
port_digest_msg.egress_port = standard_metadata.egress_spec;
port_digest_msg.port_rate = byteCount;
digest(1, port_digest_msg);
```
I am compiling the p4 code using the latest p4c for the bmv2 tagret and v1model architecture as follows :
```
docker run -it -d --privileged -v $(pwd):/root/p4src --name p4c-cr p4lang/p4c bash
docker exec -w /root/p4src -it p4c-cr p4c-bm2-ss --target bmv2 --arch v1model --std p4-16 $1.p4 -o $1.json
```
I load the json file using `pi_add_config_from_file` and set the forwarding pipeline on **simple_switch_grpc** version 1.13.0 . When I try to register the digest via P4Runtime GRPC using the digest_id 1 I get the following error : 
**`Error: 1 is not a valid digest id`** 

I tried using the name `portrate_digest_t ` to get the id with the following API but it returns 0: 
`pi_p4_id_t digest_id = pi_info_digest_id_from_name(p4info, "portrate_digest_t ");`

Everything other that digest (actions, tables, matches) is recognized properly by name in p4info. 
The json file generated contains the digest entry with the right ID 1:
 
```
 "learn_lists" : [
    {
      "id" : 1,
      "name" : "portrate_digest_t",
      "elements" : [
        {
          "type" : "field",
          "value" : ["tmp_17", "egress_port"]
        },
        {
          "type" : "field",
          "value" : ["tmp_17", "port_rate"]
        }
      ]
```
Do you have any idea why the digest is not recognized ?

**Comment by antoninbas** [comment]
The ids is in the bmv2 JSON are not valid PI / P4Runtime ids. The ids need to come from the P4Info file, which you can generate using a p4c command line flag. For an example of how to use P4Runtime with digests, please refer to https://github.com/antoninbas/p4runtime-go-client/tree/master/cmd/l2_switch.

**Comment by mohammedelazzab** [comment]
Can the p4info file be parsed by PI to get the digest_ids by name ?

**Comment by antoninbas** [comment]
I think your question is a bit confusing to me, because you are using both P4Runtime & PI, instead of a single one of them, and because your initial p4c invocation does not generate a P4Info file, which is required for P4Runtime, yet you mentioned using P4Runtime.

Anyway, the ID you share (387236398) is correct and will work with P4Runtime. If it doesn't I think you will need to provide more details so we can help you.

PI typically does not consume P4Info directly. It is sent by the client to the P4Runtime server, converted and handed over to PI.

One legacy use case was feeding the bmv2 JSON to PI (that was before P4Runtime became a thing). I don't know if that's what you are trying to do here. That code path is mostly deprecated and for this reason it was never updated to support digests:

https://github.com/p4lang/PI/blob/771d5c46106f14f33777e70f39df2ae772cdfe17/src/config_readers/bmv2_json_reader.c#L755-L763

I recommend using P4Runtime, and not make any PI calls (you should use P4Runtime over gRPC and not link your program to PI at all). Like in the example I shared above.

**Comment by mohammedelazzab** [comment]
You are right I was using PI APIs to parse the json to get `pi_p4_info` (PI) and then get IDs to sending requests via P4runtime. I am changing code now to pasre the p4info.txt to get `P4info` (P4Runtime) instead. 
Thank you Antonin
