### ISSUE TITLE
Using linux traffic control (tc) classifiers with bmv2

### ISSUE THREAD

**Issue by edgar-costa** [p4lang/behavioral-model#965]
Does any one know how to do packet marking and thus packet classification for interfaces that are attached to a `bmv2` switch?

We would like to be able to do some priority queueing but not inside the switch logic, we want to do it at the egress interface where we are already are doing some traffic shaping using `htb`. 

I tried using `tc filters` and `iptables` but packets never match and thus I can not classify them. When doing so I recalled that in the past I had a similar problem with `OVS`:

https://docs.openvswitch.org/en/latest/faq/issues/
**Q: Open vSwitch does not seem to obey my packet filter rules.**
_You cannot usefully use typical packet filters, like iptables, on physical Ethernet ports that you add to an Open vSwitch bridge. This is because Open vSwitch captures packets from the interface at a layer lower below where typical packet-filter implementations install their hooks. (This actually applies to any interface of type “system” that you might add to an Open vSwitch bridge.)_

Is the problem the same? am I doing something wrong? Is there any known workaround? 

Thanks a lot!

**Comment by antoninbas** [comment]
bmv2 uses libpcap (`pcap_sendpacket`) to receive & send packets, which on Linux is implemented using PF_PACKET sockets. It is expected that iptables would be skipped altogether.

I would however expect `tc filters` to work, but I am no expert. It would be useful if you could share your `tc` commands. I also recommend reading this email thread (https://www.spinics.net/lists/netdev/msg168967.html) which is old but seems to describes a very similar problem, and which was resolved with a simple workaround (using `protocol all` instead of `protocol ip` in the `tc` rules).

If you can't get it to work, there is also the possibility of writing a separate implementation of BMI (https://github.com/p4lang/behavioral-model/blob/master/src/BMI/bmi_interface.h) to control which socket type is used and how. I simply used libpcap because of portability.

**Comment by edgar-costa** [comment]
Thanks for the rapid response!

I read the entire email thread at the beginning a bit confused and thinking it would not work for what they were saying but.... I gave it a try, and using `protocol all` WORKS, although it will make the filter a bit less efficient but in any case 99.9% of the traffic is `ip`. 

Are you also binding to `ETH_P_ALL` ? 

Thanks a lot Antonin without knowing what was the real issue I was not able to do informed google searches. Thanks to this our students will be able to use some simple traffic classification at the P4 switch nodes 😃

**Comment by antoninbas** [comment]
> Are you also binding to `ETH_P_ALL` ?

Not directly in the bmv2 code, but I believe libpcap does in this case (which makes sense because there is no guarantee that the packets are IP), and tcpreplay is implemented similarly with libpcap.

**Comment by edgar-costa** [comment]
makes sense
